package com.vault.ui

/**
 * English copy added in the 4.0.0 release pass. Kept separate from UiText.kt so
 * the main table stays untouched; consulted only when UI_COPY/UI_DYNAMIC miss.
 */
internal val UI_COPY_EXTRA: Map<String, List<String>> = mapOf(
    "本地加密历史（20个常规版本与恢复前安全版本）" to listOf("Encrypted local history (20 regular versions and pre-restore safety versions)"),
    "历史恢复暂不支持通行密钥和已永久删除的条目" to listOf("History restore currently excludes Passkeys and permanently deleted entries"),
    "快照源已变化，请重新创建" to listOf("The snapshot source changed. Create it again"),

    "设备与历史版本" to listOf("Devices and version history"),
    "当前设备" to listOf("Current device"),
    "当前版本" to listOf("Current version"),
    "历史快照" to listOf("Historical snapshot"),
    "无已验证授权记录" to listOf("No verified authorization record"),
    "活动时间未知" to listOf("Activity time unknown"),
    "已验证的远端写入设备" to listOf("Authenticated remote writer"),
    "签名授权有效" to listOf("Signed authorization valid"),
    "签名授权已过期" to listOf("Signed authorization expired"),
    "保险库记录中授权已撤销" to listOf("Authorization revoked in vault records"),
    "操作失败" to listOf("Operation failed"),
    "此历史快照需要创建时的主密码" to listOf("This snapshot requires the master password used when it was created"),
    "历史快照已失效" to listOf("This history snapshot is no longer available"),
    "历史快照不属于当前保险库" to listOf("This snapshot does not belong to the current vault"),
    "请选择需要恢复的条目" to listOf("Choose entries to restore"),
    "保险库已变化，请重新预览历史快照" to listOf("The vault has changed. Preview the snapshot again."),
    "历史快照身份校验失败" to listOf("Snapshot identity verification failed"),
    "只能恢复历史快照中的有效条目" to listOf("Only active entries in the snapshot can be restored"),
    "已永久删除的条目不能从历史恢复" to listOf("Permanently deleted entries cannot be restored from history"),
    "设备绑定的通行密钥不能从历史恢复" to listOf("Device-bound passkeys cannot be restored from history"),
    "无法创建历史快照目录" to listOf("Could not create the history snapshot directory"),
    "无法保存快照验证信息" to listOf("Could not save snapshot verification data"),
    "无效历史快照" to listOf("Invalid history snapshot"),
    "历史快照校验失败" to listOf("History snapshot verification failed"),
    "设备名称须为 1–64 个字符" to listOf("Device names must contain 1–64 characters"),
    "查看已认证设备与本机加密历史，选择条目恢复。" to listOf("View authenticated devices and encrypted local history, and choose entries to restore."),
    "查看设备与历史" to listOf("View devices and history"),
    "设备记录来自已认证的保险库。此处不提供服务器端设备撤销。" to listOf("Device records come from the authenticated vault. Server-side device revocation is not available here."),
    "已认证设备记录" to listOf("Authenticated device record"),
    "本机昵称" to listOf("This device's nickname"),
    "保存昵称" to listOf("Save nickname"),
    "设备昵称已保存" to listOf("Device nickname saved"),
    "本地加密历史（最多20个版本）" to listOf("Encrypted local history (up to 20 versions)"),
    "历史仅保存在本机应用私有空间。恢复所选条目会创建新提交，并先保存恢复前版本；当前新增条目会保留。" to listOf("History is stored in this app's private local storage. Restoring selected entries creates a new commit after saving the current version; other current entries are preserved."),
    "创建版本" to listOf("Create version"),
    "历史版本已创建" to listOf("History version created"),
    "暂无历史版本" to listOf("No history versions yet"),
    "历史版本预览需验证；若主密码已更改，请输入该版本使用的密码。" to listOf("Version previews require authentication. If your master password has changed, enter the password used for this version."),
    "历史主密码（可选）" to listOf("Historical master password (optional)"),
    "验证并预览" to listOf("Authenticate and preview"),
    "选择要恢复的条目" to listOf("Choose entries to restore"),
    "此版本没有可恢复条目" to listOf("This version has no restorable entries"),
    "恢复所选条目" to listOf("Restore selected entries"),
    "确认恢复所选条目" to listOf("Confirm selected entry restore"),
    "同ID条目将以历史内容恢复。会先保存恢复前版本，并保留当前其他条目。" to listOf("Entries with matching IDs will receive their historical content. The current version will be saved first, and other current entries will be preserved."),
    "确认恢复" to listOf("Confirm restore"),
    "所选条目已恢复，恢复前版本已保存" to listOf("Selected entries restored; the previous version was saved"),
    "已写入云端并通过读回校验" to listOf("Written to cloud storage and verified by reading it back"),
    "远端读回文件为空" to listOf("The remote readback file is empty"),
    "远端读回内容与上传不一致" to listOf("The remote readback does not match the uploaded file"),

    "远端更新" to listOf("Remote updates"),

    "检测远端更新" to listOf("Check for remote updates"),
    "每5分钟检查一次，仅在保险库解锁且程序在前台时运行；只提醒，不会自动同步。" to listOf("Checks every 5 minutes while the vault is unlocked and the app is in the foreground. Only notifies; does not sync automatically."),
    "远端有更新" to listOf("Remote update available"),
    "远端文件已变化，尚未同步到本机" to listOf("The remote file changed and has not been synced to this device."),
    "立即同步" to listOf("Sync now"),
    "稍后处理" to listOf("Later"),
    "远端更新检测失败" to listOf("Could not check for remote updates"),

    "清除当前来源的关联与字段用途" to listOf("Clear association and field mappings for this source"),
    "已清除当前来源的关联与字段用途" to listOf("Association and field mappings cleared for this source"),
    "确认填充" to listOf("Confirm fill"),
    "此条目尚未确认与当前来源关联，请核对后填充。" to listOf("This entry has no confirmed association with this source. Check it before filling."),
    "记住与当前来源的关联" to listOf("Remember this source association"),
    "选择字段用途" to listOf("Choose the field purpose"),
    "记住此字段用途" to listOf("Remember this field purpose"),
    "已确认关联" to listOf("Confirmed association"),
    "来源匹配" to listOf("Matching source"),
    "同一网站" to listOf("Same site"),
    "名称相关" to listOf("Related name"),
    "手动选择" to listOf("Manual selection"),
    "请先验证当前主密码" to listOf("Verify the current master password first"),
    "保险库在导入期间已变化，请重新导入" to listOf("The vault changed during import. Import again."),
    "保险库身份已失效" to listOf("The vault identity is no longer valid"),
    "导出授权已过期，请重新验证主密码" to listOf("Export authorization expired. Verify the master password again."),
    "确认更新旧版应用绑定" to listOf("Confirm update to a legacy app binding"),
    "此条目没有经过当前应用签名校验。确认后会将其绑定到当前应用，并更新保存的凭据。" to listOf("This entry was not verified against the current app signature. Confirming will bind it to this app and update the saved credential."),
    "确认并更新" to listOf("Confirm and update"),
    "验证已冷却，请" to listOf("Verification is cooling down. Try again in"),
    "秒后重试" to listOf("seconds."),
    "主密码高安全模式" to listOf("High-security master password mode"),
    "开启时拒绝未达到推荐强度的主密码" to listOf("Reject master passwords below the recommended strength when enabled"),
    "建议使用随机密码或至少 5 个无关单词，空格可以保留。" to listOf("Use a random password or at least five unrelated words. Spaces are allowed."),
    "该主密码命中本地常见或泄露密码词典，不能使用。" to listOf("This master password is in the local common or breached-password blocklist and cannot be used."),
    "该主密码太容易被离线猜中，不能使用。请改用随机密码或至少 5 个无关单词。" to listOf("This master password is too easy to guess offline. Use a random password or at least five unrelated words."),
    "未达到推荐强度，高安全模式下不能使用。" to listOf("This master password is below the recommendation and cannot be used in high-security mode."),
    "该主密码偏弱，继续时必须再次确认风险。" to listOf("This master password is weak. You must confirm the risk again to continue."),
    "已达到推荐强度。" to listOf("Recommended strength reached."),
    "估计抗猜强度" to listOf("Estimated guess resistance"),
    "确认使用偏弱主密码" to listOf("Confirm weak master password"),
    "复制保险库文件后可离线猜测主密码，应用内冷却无法阻止这种攻击。建议返回并改用随机密码或至少 5 个无关单词。" to listOf("An attacker with a copy of the vault can guess the master password offline; in-app cooldowns cannot stop this. Go back and use a random password or at least five unrelated words."),
    "仍然使用" to listOf("Use anyway"),
    "返回修改" to listOf("Go back"),
    "*空*" to listOf("*Empty*"),
    "请求失败" to listOf("Request failed"),
    "30 秒" to listOf("30 seconds"),
    "60 秒" to listOf("60 seconds"),
    "PMVE Mutation 不可用" to listOf("PMVE mutation unavailable"),
    "PMVE RootKey 会话已失效" to listOf("PMVE RootKey session expired"),
    "PMVE RootKey 必须为 32 字节" to listOf("PMVE RootKey must be 32 bytes"),
    "PMVE staging kind 无效" to listOf("Invalid PMVE staging kind"),
    "PMVE 会话已失效" to listOf("PMVE session expired"),
    "PMVE 会话已锁定" to listOf("PMVE session locked"),
    "PMVE 会话缺少提交基线" to listOf("PMVE session is missing a commit baseline"),
    "PMVE 媒体会话未解锁" to listOf("PMVE media session is not unlocked"),
    "PMVE 安装后未返回 RootKey" to listOf("PMVE installation did not return a RootKey"),
    "PMVE 生物识别凭据缺少身份绑定" to listOf("PMVE biometric credential is missing an identity binding"),
    "PMVE 解锁未返回保险库身份" to listOf("PMVE unlock did not return a vault identity"),
    "PMVE 认证结果缺少 identity" to listOf("PMVE authentication result is missing identity"),
    "PMVE 身份或提交谱系无效" to listOf("Invalid PMVE identity or commit lineage"),
    "传输" to listOf("Transfer"),
    "云同步" to listOf("Cloud sync"),
    "导入导出" to listOf("Import / export"),
    "数据库维护" to listOf("Database maintenance"),
    "泄露检测" to listOf("Breach check"),
    "保险库传输中" to listOf("Vault transfer in progress"),
    "保险库传输中断" to listOf("Vault transfer interrupted"),
    "保险库传输完成" to listOf("Vault transfer complete"),
    "保险库传输已取消" to listOf("Vault transfer cancelled"),
    "保险库传输失败" to listOf("Vault transfer failed"),
    "保险库传输提示" to listOf("Vault transfer notice"),
    "传输失败" to listOf("Transfer failed"),
    "传输已完成" to listOf("Transfer complete"),
    "有内容被对方取消或拒绝" to listOf("Content was cancelled or rejected by the other device"),
    "有内容被对方取消或拒绝，其余已完成" to listOf("Some content was cancelled or rejected by the other device; the rest completed"),
    "正在连接对方设备…" to listOf("Connecting to the other device…"),
    "导入账户" to listOf("Import vault account"),
    "正在导入保险库文件…" to listOf("Importing the vault file…"),
    "FAEVault 后台任务状态已更新" to listOf("FAEVault background task status updated"),
    "应用更新" to listOf("App update"),
    "已完成" to listOf(" completed"),
    "失败" to listOf(" failed"),
    "已中断" to listOf(" interrupted"),
    "后台任务" to listOf("Background tasks"),
    "后台任务结果" to listOf("Background task results"),
    "打开应用查看详情" to listOf("Open the app for details"),
    "云端硬盘同步" to listOf("Cloud drive sync"),
    "加密备份导出" to listOf("Encrypted backup export"),
    "加密备份导入" to listOf("Encrypted backup import"),
    "加密备份已导入并合并" to listOf("Encrypted backup imported and merged"),
    "已读取加密备份，等待确认合并" to listOf("Encrypted backup read; awaiting merge confirmation"),
    "正在导出保险库文件…" to listOf("Exporting the vault file…"),
    "正在下载更新包…" to listOf("Downloading the update package…"),
    "更新包已下载并开始安装" to listOf("Update downloaded; installation started"),
    "通用压缩包导出" to listOf("Archive export"),
    "密码泄露检测" to listOf("Password breach check"),
    "正在下载并合并云端数据…" to listOf("Downloading and merging cloud data…"),
    "正在导出加密备份…" to listOf("Exporting encrypted backup…"),
    "正在导入加密备份…" to listOf("Importing encrypted backup…"),
    "正在导出压缩包…" to listOf("Exporting archive…"),
    "正在检查密码泄露…" to listOf("Checking passwords for breaches…"),
    "没有需要检测的条目" to listOf("No items need checking"),
    "Passkey 数据无效" to listOf("Invalid passkey data"),
    "本设备高安全性模式仅支持 ES256 或 RS256" to listOf("High-security mode supports only ES256 or RS256"),
    "自动填充排除项缓存保存失败" to listOf("Could not save autofill exclusion cache"),
    "保险库在编辑期间已变化，请重试" to listOf("The vault changed during editing. Try again."),
    "设备 Passkey 绑定保存失败" to listOf("Could not save the device Passkey binding"),
    "设备绑定 Passkey 在本机不可用" to listOf("This device-bound Passkey is unavailable on this device"),
    "设备绑定 Passkey 元数据不匹配" to listOf("Device-bound Passkey metadata does not match"),
    "设备绑定 Passkey 私钥已丢失" to listOf("The device-bound Passkey private key is missing"),
    "系统未返回认证后的签名操作" to listOf("The system did not return an authenticated signing operation"),
    "使用本设备高安全性 Passkey" to listOf("Use high-security Passkey on this device"),
    "验证锁屏后由 Android Keystore 完成签名" to listOf("Verify your screen lock to sign with Android Keystore"),
    "使用 Passkey" to listOf("Use Passkey"),
    "PMVE 身份缺失" to listOf("PMVE identity is missing"),
    "创建 Passkey" to listOf("Create Passkey"),
    "私钥不可导出且只存在于本机 Android Keystore；设备丢失后无法恢复。" to listOf("The private key is non-exportable and exists only in Android Keystore on this device; it cannot be recovered if the device is lost."),
    "保存新的恢复密钥" to listOf("Save the new recovery key"),
    "当前恢复密钥本次使用后会失效。请保存并重新输入下面的新密钥；无需再次进行身份验证。" to listOf("The current recovery key will expire after this use. Save and re-enter the new key below; no additional identity verification is required."),
    "新恢复密钥" to listOf("New recovery key"),
    "复制新密钥" to listOf("Copy new key"),
    "重新输入新恢复密钥" to listOf("Re-enter the new recovery key"),
    "已保存并继续" to listOf("Saved, continue"),
    "备份包含 Passkey，请使用至少 14 位且包含三类字符的强导出口令" to listOf("This backup contains Passkeys. Use an export passphrase of at least 14 characters from three character groups"),
    "保险库会话已锁定" to listOf("The vault session is locked"),
    "WebDAV 仍返回写入前版本" to listOf("WebDAV still returns the pre-write version"),
    "WebDAV 保险库文件为空" to listOf("The WebDAV vault file is empty"),
    "WebDAV 远端已由其他设备写入" to listOf("The WebDAV remote file was written by another device"),
    "WebDAV 远端已由其他设备更新" to listOf("The WebDAV remote file was updated by another device"),
    "WebDAV 远端文件在同步期间变为空" to listOf("The WebDAV remote file became empty during sync"),
    "error:回读校验失败，已保留为 .backup-partial" to listOf("Read-back verification failed; kept as .backup-partial"),
    "error:重命名失败" to listOf("Rename failed"),
    "vaultName 不能为空" to listOf("Vault name cannot be empty"),
    "● 已连接设备" to listOf("● Device connected"),
    "上传完成，正在回读安全校验…" to listOf("Upload complete; verifying by read-back…"),
    "上传覆盖完成，远端文件已通过读回校验" to listOf("Overwrite complete; the remote file passed read-back verification"),
    "下载覆盖完成，本地文件已通过写入校验" to listOf("Download complete; the local file passed write verification"),
    "不一致" to listOf("Inconsistent"),
    "不存在" to listOf("Does not exist"),
    "不完整" to listOf("Incomplete"),
    "不属于字段的附加说明" to listOf("Additional information not tied to a field"),
    "不是同一份 PMVE 保险库" to listOf("Not the same PMVE vault"),
    "不是我，断开" to listOf("Not me, disconnect"),
    "不是有效的传输站二维码" to listOf("This is not a valid transfer-station QR code"),
    "两次输入的密码不一致" to listOf("The two passwords do not match"),
    "两端不是同一份 PMVE 保险库，已取消同步" to listOf("The two vaults are not the same PMVE vault; sync was cancelled"),
    "中断" to listOf("Interrupted"),
    "主密码" to listOf("Master password"),
    "主密码/密钥版本已更新" to listOf("Master password and key version updated"),
    "主密码不匹配" to listOf("Master password does not match"),
    "主密码已更新；恢复密钥仍然有效，生物识别解锁已关闭" to listOf("Master password updated. Your recovery key remains valid; biometric unlock was disabled."),
    "主密码已重置。请重新保存一份新恢复密钥；确认前旧恢复密钥仍然有效，确认后旧密钥立即失效。此流程不可取消。" to listOf("Master password reset. Save a new recovery key now. The old key stays valid until you confirm, then it is revoked immediately. This flow cannot be cancelled."),
    "主密码已重置，请重新保存恢复密钥" to listOf("Master password reset. Save a new recovery key."),
    "二维码" to listOf("QR code"),
    "二维码无效、来源不明或已过期" to listOf("The QR code is invalid, from an unknown source, or has expired"),
    "云端" to listOf("Cloud"),
    "云端仍返回写入前版本" to listOf("Cloud still returns the pre-write version"),
    "云端保险库文件为空" to listOf("The cloud vault file is empty"),
    "云端发布期间本地保险库已更新，等待重新合并" to listOf("The local vault changed during publishing; waiting to merge again"),
    "云端响应超时，请检查网络后重试" to listOf("The cloud request timed out. Check your network and try again."),
    "云端回读文件为空" to listOf("The cloud read-back file is empty"),
    "云端提供程序未返回具体错误，请检查网络、权限和剩余空间" to listOf("The cloud provider returned no specific error. Check your network, permissions and free space."),
    "云端文件不属于当前保险库，请重新关联正确文件" to listOf("The cloud file does not belong to the current vault. Reconnect the correct file."),
    "云端文件超过 1 GB 安全限制" to listOf("The cloud file exceeds the 1 GB safety limit"),
    "云端登录信息已失效，请重新关联" to listOf("Cloud sign-in is no longer valid. Reconnect."),
    "云端硬盘同步失败" to listOf("Cloud Drive sync failed"),
    "云端空间或账户配额不足，请释放空间后重试" to listOf("Cloud storage or account quota is full. Free up space and try again."),
    "云端身份验证失败，请检查服务器证书或重新关联" to listOf("Cloud authentication failed. Check the server certificate or reconnect."),
    "仅支持 PMVE 生物识别凭据" to listOf("Only PMVE biometric credentials are supported"),
    "仍然导入" to listOf("Import anyway"),
    "从相册选择二维码图片" to listOf("Choose a QR code image from Gallery"),
    "会话密钥已失效" to listOf("The session key has expired"),
    "传输内容未通过完整性校验，多次重试后仍不一致；未保存不完整数据。请保持网络稳定并重新同步。" to listOf("The transfer failed integrity checks and stayed inconsistent after retries. Incomplete data was not saved. Keep the network stable and sync again."),
    "传输大文件" to listOf("Transfer large files"),
    "传输已中断，请重新连接" to listOf("Transfer interrupted. Reconnect."),
    "传输文本" to listOf("Send text"),
    "传输站地址" to listOf("Transfer station address"),
    "传输站已开启，等待其他设备连接" to listOf("Transfer station is on. Waiting for another device to connect."),
    "传输站等待连接超时，已停止" to listOf("The transfer station timed out waiting for a connection and was stopped."),
    "传输记录" to listOf("Transfer history"),
    "使用当前位置" to listOf("Use current location"),
    "保存失败" to listOf("Save failed"),
    "保留" to listOf("Keep"),
    "保险库 ID" to listOf("Vault ID"),
    "保险库 id 不一致" to listOf("Vault ID mismatch"),
    "保险库会话已失效" to listOf("Vault session expired"),
    "请先解锁保险库" to listOf("Unlock the vault first"),
    "保险库会话已变化" to listOf("The vault session changed"),
    "保险库会话已失效，请重新解锁后重试" to listOf("Vault session expired. Unlock again and retry."),
    "保险库尚未解锁" to listOf("The vault is not unlocked"),
    "保险库已变化，请重试" to listOf("The vault changed. Try again."),
    "保险库已自动压缩，历史空间已回收" to listOf("The vault was compacted automatically; history space was reclaimed."),
    "保险库已锁定" to listOf("The vault is locked"),
    "保险库文件已导出" to listOf("Vault file exported"),
    "停止接收" to listOf("Stop receiving"),
    "允许发送账户数据？" to listOf("Allow sending vault data?"),
    "允许本次发送" to listOf("Allow this send"),
    "允许本次同步" to listOf("Allow this sync"),
    "允许此设备同步？" to listOf("Allow this device to sync?"),
    "关联文件没有可用的读写权限，请重新关联并授予读写权限" to listOf("The linked file has no read/write access. Reconnect and grant access."),
    "内容" to listOf("Content"),
    "写入前版本" to listOf("Pre-write version"),
    "冲突" to listOf("Conflict"),
    "切到后台时从最近任务中隐藏" to listOf("Hide from recent tasks when backgrounded"),
    "创建并加密保存 Passkey" to listOf("Create and save a passkey securely"),
    "剪贴板中没有可粘贴的内容" to listOf("No content is available in the clipboard to paste"),
    "剪贴板中没有可发送的内容" to listOf("No sendable content in the clipboard"),
    "未连接，请先建立传输连接" to listOf("Not connected. Establish a transfer connection first"),
    "读取剪贴板内容失败" to listOf("Failed to read clipboard content"),
    "已开始发送" to listOf("Transfer started"),
    "卡号" to listOf("Card number"),
    "双方均有修改，可自动合并" to listOf("Both sides changed and can be merged automatically"),
    "双方提交分叉，可自动合并" to listOf("Commits forked on both sides and can be merged automatically"),
    "发行方" to listOf("Issuer"),
    "发送" to listOf("Send"),
    "发送中" to listOf("Sending"),
    "发送内容" to listOf("Send content"),
    "发送文件" to listOf("Send file"),
    "发送图片" to listOf("Send image"),
    "粘贴" to listOf("Paste"),
    "剪切" to listOf("Cut"),
    "复制文本" to listOf("Copy text"),
    "发送文件失败" to listOf("Failed to send file"),
    "发送文件超过 10 TiB 溢出护栏" to listOf("The file exceeds the 10 TiB overflow guardrail"),
    "发送文本失败" to listOf("Failed to send text"),
    "取消关联" to listOf("Disconnect"),
    "另一台设备尚未允许发送数据" to listOf("The other device has not allowed sending data yet"),
    "另一台设备已拒绝请求或连接已经失效" to listOf("The other device rejected the request or the connection is no longer valid"),
    "另一台设备希望与本机双向同步，会读取并写入当前账户的密码、验证码和附件。" to listOf("The other device wants to sync both ways and will read and write this vault's passwords, codes and attachments."),
    "另一台设备希望复制当前账户的全部内容，包括密码、验证码和附件。" to listOf("The other device wants to copy this vault's entire contents, including passwords, codes and attachments."),
    "另一台设备没有确认发送，请重新连接后再试" to listOf("The other device did not confirm the send. Reconnect and try again."),
    "只会复制账户，不会删除或修改另一台设备上的内容。" to listOf("Only the vault is copied; nothing on the other device is deleted or modified."),
    "只读" to listOf("Read-only"),
    "可能系统拒绝了 \"读取应用列表\" 权限。\n请到应用权限设置中开启。" to listOf("The system may have denied the “Read installed apps” permission.\nEnable it in app permissions."),
    "合并" to listOf("Merge"),
    "同步" to listOf("Sync"),
    "同步完成" to listOf("Sync complete"),
    "关闭页面" to listOf("Close page"),
    "同步仍在进行，中断会放弃本次合并与回传，尚未完成的部分需要重新同步。确定要断开吗？" to listOf("Sync is still running. Disconnecting abandons this merge and upload; unfinished parts must be synced again. Disconnect anyway?"),
    "已发送本地数据，并完成对方回传数据的校验与合并。" to listOf("Local data sent; returned data verified and merged."),
    "本机角色：传输站" to listOf("This device: transfer station"),
    "本机角色：连接方" to listOf("This device: connecting device"),
    "数据关系：双方一致" to listOf("Data relationship: identical"),
    "数据关系：已采用对方的新版本" to listOf("Data relationship: adopted the newer remote version"),
    "数据关系：保留本地较新版本" to listOf("Data relationship: kept the newer local version"),
    "数据关系：双方修改已合并" to listOf("Data relationship: changes from both devices merged"),
    "通行密钥冲突" to listOf("Passkey conflicts"),
    "本地数据已发送 · 对方回传已接收 · 数据校验：通过" to listOf("Local data sent · Returned data received · Data verification: passed"),
    "已断开连接" to listOf("Disconnected"),
    "将关闭当前传输页面并回到扫码连接页。" to listOf("Close this transfer page and return to scan/connect."),
    "已完成拉取、合并和回传。" to listOf("Download, merge and upload completed."),
    "上传远端：成功 · 数据校验：通过" to listOf("Upload: successful · Data verification: passed"),
    "上传远端：成功 · 数据校验：未执行" to listOf("Upload: successful · Data verification: not performed"),
    "上传远端：未执行，内容一致 · 数据校验：通过" to listOf("Upload: skipped, content matches · Data verification: passed"),
    "上传远端：未执行，内容一致 · 数据校验：未执行" to listOf("Upload: skipped, content matches · Data verification: not performed"),
    "同步完成 · 内容已是最新" to listOf("Sync complete · Already up to date"),
    "同步完成，传输站已关闭" to listOf("Sync complete; the transfer station was closed"),
    "同步已取消" to listOf("Sync cancelled"),
    "同步或传输进行中，请结束后再开启传输站" to listOf("A sync or transfer is in progress. Finish it before starting the transfer station."),
    "同步期间对方数据发生变化，当前结果未覆盖远端。请保持两端在线并重新同步；系统会重新拉取并合并最新版本。" to listOf("The other side changed data during sync, so the result did not overwrite the remote. Keep both devices online and sync again; the latest version will be pulled and merged automatically."),
    "同步期间远端又有新提交；系统已自动重拉并合并，达到重试上限后仍持续变化。请暂停其他设备编辑后再次同步" to listOf("The remote received new commits during sync; the system re-pulled and merged, but changes kept arriving after the retry limit. Pause editing on other devices and sync again."),
    "同步未完成，本地数据已安全保留" to listOf("Sync did not finish; local data was kept safely"),
    "后台界面隐藏" to listOf("Hide when backgrounded"),
    "启用本地备份" to listOf("Enable local backup"),
    "周期" to listOf("Period"),
    "回收站条目超过设定天数后自动彻底删除" to listOf("Trash items older than the selected period are deleted automatically"),
    "回读" to listOf("Read-back"),
    "图像加载中" to listOf("Loading image"),
    "图片中没有有效的 OTP 二维码" to listOf("No valid OTP QR code was found in the image"),
    "图片中没有识别到可用的二维码" to listOf("No usable QR code was found in the image"),
    "图片导入校验失败，图片可能已损坏" to listOf("Image import verification failed; the image may be damaged"),
    "图片尚未导入完成，请稍后查看" to listOf("This image is still being imported. Check back in a moment."),
    "图片已保存" to listOf("Image saved"),
    "图片数据为空" to listOf("The image data is empty"),
    "图片数据校验失败，可能已损坏" to listOf("Image verification failed; the image may be damaged"),
    "图片文件不存在" to listOf("The image file does not exist"),
    "图片读取失败" to listOf("Could not read the image"),
    "地址已复制，可粘贴到另一台设备" to listOf("Address copied. Paste it on the other device."),
    "地址未包含有效 PIN，请粘贴传输站的完整地址" to listOf("The address has no valid PIN. Paste the transfer station's full address"),
    "备份" to listOf("Backup"),
    "备份口令错误或文件已损坏" to listOf("Incorrect backup passphrase or the file is damaged"),
    "备份目录未授予持久读写权限，选择未保存" to listOf("The backup folder was not granted persistent read/write access. The selection was not saved."),
    "备份设备" to listOf("Backup device"),
    "多次检查仍未通过，文件未保存" to listOf("Repeated checks failed; the file was not saved"),
    "多次检查仍未通过，文件未发送" to listOf("Repeated checks failed; the file was not sent"),
    "失败" to listOf("Failed"),
    "如果长期未加载完成，请退出后重新查看" to listOf("If this takes too long, close the viewer and reopen it."),
    "媒体导入分类无效" to listOf("Invalid media import category"),
    "存在传输失败的项目" to listOf("Some transfers failed"),
    "完全一致" to listOf("Identical"),
    "完成前退出将丢失本次添加内容，不影响已保存数据" to listOf("Leaving before it finishes loses this batch only; saved data is unaffected."),
    "完成并进入保险库" to listOf("Finish and open the vault"),
    "定期把保险库文件备份到本机目录或外接U盘/硬盘" to listOf("Back up the vault file to a local folder or external USB drive on a schedule"),
    "实时" to listOf("Real time"),
    "密码冲突" to listOf("Password conflict"),
    "密钥更新时间" to listOf("Key updated"),
    "密钥版本" to listOf("Key version"),
    "对方保险库当前已锁定或仍在等待确认。请解锁对方设备并重新允许本次同步。" to listOf("The other vault is locked or still waiting for confirmation. Unlock that device and allow this sync again."),
    "对方保险库未通过当前账户密钥认证。请确认两端打开的是同一账户且均已正常解锁；本地数据未修改。" to listOf("The other vault failed key authentication for this account. Make sure both devices opened the same vault and are unlocked; local data was not modified."),
    "对方保险库的提交身份或版本谱系未通过安全检查。请重新建立传输站并确认两端账户，当前数据未被覆盖。" to listOf("The other vault's commit identity or lineage failed security checks. Recreate the transfer station and confirm both accounts; current data was not overwritten."),
    "对方尚未授权本设备读写保险库。请在传输站一方确认“允许本次同步”，然后保持两端页面开启。" to listOf("The other device has not authorized this device to read or write the vault. Confirm “Allow this sync” on the transfer station and keep both pages open."),
    "对方已关闭传输连接" to listOf("The other device closed the transfer connection"),
    "对方已关闭传输连接，未完成的项目已中断" to listOf("The other device closed the connection; unfinished transfers were interrupted"),
    "对方已断开连接" to listOf("The other device disconnected"),
    "对方已取消该文件或传输记录已失效，请重新发送" to listOf("The other device cancelled that file or its transfer record expired. Send it again."),
    "对方已同步：内容一致" to listOf("Other side synced: contents match"),
    "对方已同步：本端数据较新，已保留" to listOf("Other side synced: local data is newer and was kept"),
    "对方已拒绝或撤销本次文件传输授权" to listOf("The other device rejected or revoked authorization for this file transfer"),
    "对方已取消或拒绝接收该文件，已停止发送" to listOf("The other device canceled or rejected receiving this file. Sending stopped."),
    "对方已取消发送该文件，已停止接收" to listOf("The other device canceled sending this file. Receiving stopped."),
    "导入失败" to listOf("Import failed"),
    "导入完成：" to listOf("Import complete: "),
    "导入文件中未识别到条目" to listOf("No supported items were found in the import file"),
    "尚未同步" to listOf("Not synced yet"),
    "尚未关联" to listOf("Not connected"),
    "尚未执行" to listOf("Not run yet"),
    "尚无传输记录" to listOf("No transfers yet"),
    "未启用" to listOf("Not enabled"),
    "未命名二维码" to listOf("Untitled QR code"),
    "未完成授权" to listOf("Authorization incomplete"),
    "未执行" to listOf("Not run"),
    "未执行，内容一致" to listOf("Not run, contents match"),
    "未找到与当前应用或网站匹配的登录条目" to listOf("No login matches this app or website"),
    "未授权" to listOf("Not authorized"),
    "未知的上传同步关系" to listOf("Unknown upload-sync relationship"),
    "未能接收账户数据，请重新连接后再试" to listOf("Could not receive vault data. Reconnect and try again."),
    "未选择备份目录" to listOf("No backup folder selected"),
    "本地 PMVE 身份认证失败" to listOf("Local PMVE identity authentication failed"),
    "本地与远端为同一提交，内容一致" to listOf("Local and remote are the same commit; contents match"),
    "本地为远端后代提交，可安全上传" to listOf("Local is a descendant of remote; safe to upload"),
    "本地保险库大小为 0 或超过 1 GB 安全限制" to listOf("The local vault is empty or exceeds the 1 GB safety limit"),
    "本地保险库状态已失效" to listOf("Local vault state is no longer valid"),
    "本地保险库身份缺失" to listOf("Local vault identity is missing"),
    "本地备份" to listOf("Local backup"),
    "本地有新版本，可上传" to listOf("Local has a newer version; ready to upload"),
    "本机存储" to listOf("Local storage"),
    "本次接收可能因网络中断而损坏。为保护账户，这些数据不会被保存。" to listOf("This transfer may have been corrupted by a network interruption. To protect the vault, this data was not saved."),
    "本次提交" to listOf("This commit"),
    "权限" to listOf("Permission"),
    "查看" to listOf("View"),
    "查询会话不可用" to listOf("Query session unavailable"),
    "校验" to listOf("Verification"),
    "格式" to listOf("Format"),
    "检查已通过，正在添加到账户列表。" to listOf("Checks passed. Adding the vault to the account list."),
    "检测到同一份账户" to listOf("The same vault was detected"),
    "正在上传合并结果…" to listOf("Uploading the merged result…"),
    "正在上传并关联云端保险库…" to listOf("Uploading and linking the cloud vault…"),
    "正在下载并关联云端保险库…" to listOf("Downloading and linking the cloud vault…"),
    "正在下载并验证云端数据…" to listOf("Downloading and verifying cloud data…"),
    "正在保存" to listOf("Saving"),
    "正在保存账户" to listOf("Saving vault"),
    "正在关联…" to listOf("Connecting…"),
    "正在写入加密保险库文件…" to listOf("Writing the encrypted vault file…"),
    "正在创建云端保险库文件…" to listOf("Creating the cloud vault file…"),
    "正在发送数据给传输站…" to listOf("Sending data to the transfer station…"),
    "正在同步并关联云端保险库…" to listOf("Syncing and linking the cloud vault…"),
    "正在备份…" to listOf("Backing up…"),
    "正在导入" to listOf("Importing"),
    "正在导入图片" to listOf("Importing image"),
    "正在导入附件" to listOf("Importing attachment"),
    "正在建立加密局域网连接…" to listOf("Establishing an encrypted local network connection…"),
    "正在连接并验证设备…" to listOf("Connecting and verifying the device…"),
    "正在与对方同步…" to listOf("Syncing with the other device…"),
    "正在接收对方同步数据…" to listOf("Receiving sync data from the other device…"),
    "正在发送保险库数据…" to listOf("Sending vault data…"),
    "备份设备未连接" to listOf("Backup device not connected"),
    "备份设备状态异常" to listOf("Backup device status abnormal"),
    "设备不匹配，请连接备份目标设备" to listOf("Device mismatch. Connect the backup target device"),
    "允许此存储设备用于同步" to listOf("Allow this storage device for sync"),
    "允许并建立绑定" to listOf("Allow and bind"),
    "FAEVault 将在所选目录写入设备 UUID，并把它与本次系统目录授权绑定。只有两项身份都匹配时才会自动同步；设备疑似变化时需要再次确认。" to listOf("FAEVault will write a device UUID to the selected folder and bind it to this system folder authorization. Automatic sync runs only when both identities match; suspected changes require confirmation again."),
    "身份异常，同步设备身份不匹配，已禁止同步" to listOf("Identity anomaly: synced device identity mismatch; sync is blocked."),
    "断开连接" to listOf("Disconnect"),
    "已断开同步连接" to listOf("Sync connection disconnected"),
    "正在接收…" to listOf("Receiving…"),
    "正在接收另一台设备的数据…" to listOf("Receiving data from the other device…"),
    "正在接收账户数据" to listOf("Receiving vault data"),
    "正在检查所选云端目录…" to listOf("Checking the selected cloud folder…"),
    "正在检查收到的数据" to listOf("Checking the received data"),
    "正在清理…" to listOf("Cleaning…"),
    "正在确认收到的数据完整且未被更改。" to listOf("Confirming the received data is complete and unchanged."),
    "正在识别备份设备…" to listOf("Identifying the backup device…"),
    "正在识别远端保险库文件…" to listOf("Identifying the remote vault file…"),
    "正在读取并验证所选保险库文件…" to listOf("Reading and verifying the selected vault file…"),
    "正在选择…" to listOf("Selecting…"),
    "正在验证 WebDAV 连接，请稍候…" to listOf("Verifying the WebDAV connection…"),
    "每月" to listOf("Monthly"),
    "每小时" to listOf("Hourly"),
    "没有保存接收文件的权限，请检查存储权限和目标目录" to listOf("No permission to save received files. Check storage permissions and the target folder."),
    "没有新变化" to listOf("No new changes"),
    "没有读取源文件的权限，请重新选择文件并授权访问" to listOf("No permission to read the source file. Choose it again and grant access."),
    "添加" to listOf("Add"),
    "添加后，排除的应用或网站将不显示自动填充建议" to listOf("Excluded apps and websites won't show autofill suggestions"),
    "点击复制文本" to listOf("Tap to copy text"),
    "点击打开文件" to listOf("Tap to open file"),
    "生成密码并填充" to listOf("Generate password and fill"),
    "生物识别凭据与当前保险库身份不匹配，已清除" to listOf("The biometric credential does not match this vault's identity and was removed"),
    "生物识别解锁失败，请使用主密码" to listOf("Biometric unlock failed. Use the master password."),
    "登录条目已变化，请重试" to listOf("The login item changed. Try again."),
    "目录不可用或未连接时自动等待，不报错" to listOf("If the folder is unavailable or disconnected, wait automatically without an error"),
    "相机权限已被永久拒绝，请前往系统设置手动授予" to listOf("Camera permission was permanently denied. Grant it manually in system settings."),
    "继续自动填充" to listOf("Continue autofill"),
    "关闭后可能暂时无法再次唤起自动填充窗口。" to listOf("After closing, the autofill window might not be available again immediately."),
    "确认关闭" to listOf("Confirm closing"),
    "确认关闭传输站？" to listOf("Close the transfer station?"),
    "确认密码" to listOf("Confirm password"),
    "确认并锁定" to listOf("Confirm and lock"),
    "确认结束" to listOf("Confirm ending"),
    "确认结束传输？" to listOf("End the transfer?"),
    "票据" to listOf("Token"),
    "移入" to listOf("Move to"),
    "移除" to listOf("Remove"),
    "空间" to listOf("Storage"),
    "空间不足，已跳过本次备份" to listOf("Insufficient storage; this backup was skipped"),
    "立即备份" to listOf("Back up now"),
    "端口" to listOf("Port"),
    "等待主机确认导出超时" to listOf("Timed out waiting for the host to confirm the export"),
    "等待主机确认同步超时" to listOf("Timed out waiting for the host to approve the sync"),
    "等待主机确认文件传输超时" to listOf("Timed out waiting for the host to approve the file transfer"),
    "等待其他设备扫码连接" to listOf("Waiting for another device to scan and connect"),
    "等待另一台设备确认" to listOf("Waiting for the other device to confirm"),
    "等待对方响应超时。请保持两端应用在前台、网络连接稳定，并重新建立传输站后重试。" to listOf("Timed out waiting for the other device. Keep both apps in the foreground with a stable network, recreate the transfer station, and try again."),
    "等待接收" to listOf("Waiting to receive"),
    "等待网络连接" to listOf("Waiting for network"),
    "等待设备状态" to listOf("Waiting for the device"),
    "等待连接超时" to listOf("Timed out waiting for a connection"),
    "签发日期" to listOf("Issued"),
    "签发机关" to listOf("Issuing authority"),
    "签名" to listOf("Signature"),
    "算法" to listOf("Algorithm"),
    "管理密码" to listOf("Manage password"),
    "管理排除项" to listOf("Manage exclusions"),
    "结束传输" to listOf("End transfer"),
    "继续传输" to listOf("Continue transfer"),
    "继续后将立即开始传输，本次会话不再提示。" to listOf("The transfer starts immediately. You won't be asked again in this session."),
    "自动压缩至少间隔 24 小时，导入完成后 24 小时内不压缩" to listOf("Automatic compaction runs at least 24 hours apart and never within 24 hours of an import"),
    "自动填充排除" to listOf("Autofill exclusion"),
    "自动清理规则" to listOf("Automatic cleanup rules"),
    "补充内容" to listOf("Additional content"),
    "补充额外说明" to listOf("Add extra notes"),
    "解锁" to listOf("Unlock"),
    "解锁保险库" to listOf("Unlock the vault"),
    "解锁成功" to listOf("Vault unlocked"),
    "认证失败" to listOf("Authentication failed"),
    "让另一台设备扫描上方二维码，或手动输入地址和 PIN 连接" to listOf("Have the other device scan the QR code above, or connect by entering the address and PIN manually"),
    "设备剩余存储空间不足，文件未完整保存" to listOf("Not enough storage left on this device; the file was not fully saved"),
    "设备密钥保存不可用" to listOf("Device key saving is unavailable"),
    "设备密钥全量解锁不可用" to listOf("Full device-key unlock is unavailable"),
    "设备解锁信封与当前 PMVE 身份不匹配" to listOf("The device unlock envelope does not match the current PMVE identity"),
    "设置新的主密码" to listOf("Set a new master password"),
    "证书" to listOf("Certificate"),
    "证件类型" to listOf("Document type"),
    "请先设置新的主密码，恢复密钥仍然有效；完成后下一步重新保存恢复密钥。此流程不可取消。" to listOf("Set a new master password first; your recovery key stays valid. Next, save a new recovery key. This flow cannot be cancelled."),
    "请在另一台设备上确认发送。确认前不会传输任何账户数据。" to listOf("Confirm the send on the other device. No vault data is transferred before confirmation."),
    "请确认连接是你本人发起的。本次允许只用于这一次传输，完成后自动失效。" to listOf("Confirm that you initiated this connection. This approval is valid for this transfer only and expires when it finishes."),
    "请确认连接是你本人发起的。本次允许只用于这一次同步，完成后自动失效。" to listOf("Confirm that you initiated this connection. This approval is valid for this sync only and expires when it finishes."),
    "请粘贴另一台设备显示的完整连接地址" to listOf("Paste the full connection address shown on the other device"),
    "读取到的文件大小与选择时不一致" to listOf("The file size read differs from the selection"),
    "读回校验" to listOf("Read-back verification"),
    "谱系" to listOf("Lineage"),
    "账号" to listOf("Account"),
    "帐号" to listOf("Account"),
    "账户不存在" to listOf("Vault not found"),
    "账户名不合法" to listOf("Enter a valid vault name"),
    "账户名称冲突" to listOf("Vault name conflict"),
    "账户已存在" to listOf("A vault with that name already exists"),
    "超时" to listOf("Timeout"),
    "身份" to listOf("Identity"),
    "身份认证失败" to listOf("Identity authentication failed"),
    "输入完整恢复密钥以解锁。解锁后将立即进入「重新保存恢复密钥」和「设置新主密码」流程，请按提示完成。" to listOf("Enter the full recovery key to unlock. You will then be guided through saving a new recovery key and setting a new master password."),
    "输入文本，长按可粘贴剪贴板内容" to listOf("Type a message; long-press the field to paste clipboard content"),
    "过大" to listOf("Too large"),
    "远端 PMVE 文件认证失败" to listOf("Remote PMVE file authentication failed"),
    "远端 PMVE 身份或提交谱系无效" to listOf("Invalid remote PMVE identity or commit lineage"),
    "远端 PMVE 身份或提交谱系无效，已取消同步" to listOf("Invalid remote PMVE identity or commit lineage; sync was cancelled"),
    "远端不是同一份 PMVE 保险库" to listOf("The remote is not the same PMVE vault"),
    "远端不是同一份保险库" to listOf("The remote is not the same vault"),
    "远端不是同一份保险库，已拒绝" to listOf("The remote is not the same vault; it was rejected"),
    "远端不是有效的 PMVE 保险库" to listOf("The remote is not a valid PMVE vault"),
    "远端与本地提交关系无法认证" to listOf("The commit relationship between remote and local could not be authenticated"),
    "远端为本地后代提交，可安全拉取合并" to listOf("Remote is a descendant of local; safe to pull and merge"),
    "远端保险库密钥版本未能同步" to listOf("The remote vault key version could not be synced"),
    "远端保险库格式不受支持或文件已损坏，请确认关联的是当前账户的 PMVE 文件" to listOf("The remote vault format is unsupported or the file is damaged. Confirm you linked the current vault's PMVE file."),
    "远端保险库格式与本地 PMVE 不一致" to listOf("The remote vault format differs from local PMVE"),
    "远端保险库格式与本地 PMVE 不一致，已取消同步" to listOf("The remote vault format differs from local PMVE; sync was cancelled"),
    "远端内容校验" to listOf("Remote content verification"),
    "远端同步会话已失效" to listOf("The remote sync session has expired"),
    "远端数据无法用当前账户验证，请确认关联的是同一份保险库" to listOf("Remote data could not be verified with this account. Confirm you linked the same vault."),
    "远端文件不存在或为空" to listOf("The remote file does not exist or is empty"),
    "远端文件下载失败：未知错误" to listOf("Failed to download the remote file: unknown error"),
    "远端文件不属于当前账户，本次同步已停止" to listOf("The remote file does not belong to this account; sync was stopped"),
    "远端文件修改时间尚未更新" to listOf("The remote file's modification time has not updated yet"),
    "远端文件在同步期间变为空" to listOf("The remote file became empty during sync"),
    "远端文件大小尚未更新" to listOf("The remote file size has not updated yet"),
    "远端文件已由其他设备写入" to listOf("The remote file was written by another device"),
    "远端文件已由其他设备更新" to listOf("The remote file was updated by another device"),
    "远端文件未通过安全检查，本次同步已停止" to listOf("The remote file failed security checks; sync was stopped"),
    "远端最终文件不属于当前保险库" to listOf("The final remote file does not belong to the current vault"),
    "远端有新版本，可拉取" to listOf("Remote has a newer version; ready to pull"),
    "连接保持开启，任意一方都可以发送" to listOf("The connection stays open; either side can send"),
    "连接地址不完整，请从另一台设备重新复制" to listOf("The connection address is incomplete. Copy it again from the other device."),
    "连接地址已失效" to listOf("The connection address has expired"),
    "连接地址已失效，请从另一台设备重新复制" to listOf("The connection address has expired. Copy it again from the other device."),
    "连接失败，请重试" to listOf("Connection failed. Try again."),
    "连接将立即关闭，尚未完成的发送或接收会被中断；已完成的传输记录会保留到离开当前页面。" to listOf("The connection closes immediately and unfinished transfers are interrupted. Completed transfer records stay until you leave this page."),
    "连接已中断，请保持两台设备在同一局域网并重新尝试" to listOf("The connection was interrupted. Keep both devices on the same network and try again."),
    "连接已中断，请确认两台设备仍在同一网络后重试" to listOf("The connection was interrupted. Confirm both devices are still on the same network and try again."),
    "连接已断开，传输中断" to listOf("The connection closed; the transfer was interrupted"),
    "连接码不正确，请重新扫描最新二维码" to listOf("The connection code is incorrect. Scan the latest QR code."),
    "连接码或配对地址已失效。请从对方设备重新建立传输站，并使用最新二维码或完整地址连接。" to listOf("The connection code or pairing address has expired. Recreate the transfer station on the other device and connect with the latest QR code or full address."),
    "连接等待时间过长，请确认两台设备在同一局域网后重试" to listOf("The connection wait took too long. Confirm both devices are on the same network and try again."),
    "选择备份目录" to listOf("Choose backup folder"),
    "选择应用" to listOf("Choose app"),
    "通过" to listOf("Passed"),
    "通过 Credential Manager 保存密码" to listOf("Save password with Credential Manager"),
    "邮件" to listOf("Email"),
    "邮箱" to listOf("Email"),
    "电话" to listOf("Phone"),
    "邮编" to listOf("Postal code"),
    "自动填充类型" to listOf("Autofill type"),
    "按名称精确匹配" to listOf("Match exact field name"),
    "不自动填充" to listOf("Do not autofill"),
    "一次性验证码" to listOf("One-time code"),
    "姓名" to listOf("Full name"),
    "国家 / 地区" to listOf("Country / region"),
    "省 / 州" to listOf("State / province"),
    "城市" to listOf("City"),
    "详细地址" to listOf("Street address"),
    "持卡人" to listOf("Cardholder"),
    "有效期" to listOf("Expiry"),
    "安全码" to listOf("Security code"),
    "证件号码" to listOf("Document number"),
    "API 凭证" to listOf("API credentials"),
    "API 密文" to listOf("API secret"),
    "主机" to listOf("Host"),
    "数据库" to listOf("Database"),
    "Wi-Fi 名称" to listOf("Wi-Fi name"),
    "Wi-Fi 密码" to listOf("Wi-Fi password"),
    "恢复答案" to listOf("Recovery answer"),
    "自定义文本" to listOf("Custom text"),
    "自定义密文" to listOf("Custom secret"),
    "不可用" to listOf("Unavailable"),
    "配对" to listOf("Pairing"),
    "配额" to listOf("Quota"),
    "重新保存恢复密钥" to listOf("Save a new recovery key"),
    "重新接收" to listOf("Receive again"),
    "银行" to listOf("Bank"),
    "附件导出校验失败，数据可能已损坏" to listOf("Attachment export verification failed; the data may be damaged"),
    "附件文件不存在" to listOf("The attachment file does not exist"),
    "附件是空文件" to listOf("The attachment is empty"),
    "附件超过允许的容量" to listOf("The attachment exceeds the allowed size"),
    "需要有效的 6 位 PIN 码" to listOf("A valid 6-digit PIN is required"),
    "预览图解码失败" to listOf("Could not decode the preview image"),
    "验证并解锁" to listOf("Verify and unlock"),
    "验证码" to listOf("Verification code"),
    "验证错误：多次核对失败，已重新开始保存流程，请重新核对密钥。" to listOf("Verification error: too many failed checks. The save flow restarted; verify the key again."),
    "接收" to listOf("Receive"),
    "接收中" to listOf("Receiving"),
    "接收文本" to listOf("Receive text"),
    "开始导入" to listOf("Start import"),
    "开始清理" to listOf("Start cleanup"),
    "当前保险库为旧格式，云同步预览已不适用，请先升级到 PMVE" to listOf("This vault uses an old format, so cloud sync preview no longer applies. Upgrade to PMVE first."),
    "当前保险库名称缺失" to listOf("The current vault name is missing"),
    "待导入媒体必须是字符串引用" to listOf("Media to import must be a string reference"),
    "待导入媒体文件不存在" to listOf("The media file to import does not exist"),
    "恢复密钥已在同步中更新，本端已自动采用最新版本。\n\n确认后继续使用。" to listOf("A newer recovery key arrived through sync and was adopted automatically.\n\nConfirm to continue."),
    "恢复密钥已更新并保存，旧恢复密钥已失效" to listOf("A new recovery key was saved; the old key no longer works"),
    "恢复密钥已重新生成，旧密钥已失效" to listOf("A new recovery key is active; the previous key no longer works"),
    "恢复密钥版本已更新" to listOf("Recovery key version updated"),
    "恢复密钥验证通过，请先设置新的主密码" to listOf("Recovery key verified. Set a new master password."),
    "手动输入传输站完整地址" to listOf("Enter the full transfer station address"),
    "扫描二维码传输文件" to listOf("Scan QR code to transfer files"),
    "扫码或输入地址连接后自动进入文件传输，双方互传文件与文本。" to listOf("After scanning or entering the address, the file transfer page opens automatically and both sides can exchange files and text."),
    "数据导入/导出" to listOf("Data import/export"),
    "文件互传" to listOf("File transfer"),
    "文件互传已连接，双方均可发送" to listOf("File transfer connected; both sides can send"),
    "文件传输" to listOf("File transfer"),
    "文件传输连接将立即关闭，尚未完成的发送或接收会被中断。" to listOf("The file transfer connection closes immediately and unfinished sends or receives are interrupted."),
    "文件尚未传输完成" to listOf("The file has not finished transferring"),
    "文件认证失败" to listOf("File authentication failed"),
    "文件超过当前传输安全上限，未开始传输" to listOf("The file exceeds the current transfer safety limit and was not sent"),
    "文本超过 1 MB，请作为文件打开" to listOf("Text over 1 MB; open it as a file instead"),
    "新密码" to listOf("New password"),
    "无法写入下载文件" to listOf("Could not write the download file"),
    "无法写入云端文件" to listOf("Could not write the cloud file"),
    "无法写入恢复单文件" to listOf("Could not write the recovery sheet file"),
    "无法写入所选位置" to listOf("Could not write to the selected location"),
    "无法创建 PMVE 媒体暂存目录" to listOf("Could not create the PMVE media staging folder"),
    "无法创建下载文件" to listOf("Could not create the download file"),
    "无法创建公共下载目录" to listOf("Could not create the public Downloads folder"),
    "无法创建图片查看缓存目录" to listOf("Could not create the image viewer cache folder"),
    "无法判断待导入媒体类型" to listOf("Could not determine the type of media to import"),
    "无法发布 PMVE 媒体暂存文件" to listOf("Could not publish the PMVE staged media file"),
    "无法打开" to listOf("Could not open"),
    "无法打开保险库" to listOf("Could not open the vault"),
    "无法打开所选文件" to listOf("Could not open the selected file"),
    "无法识别稳定的设备身份，已拒绝备份" to listOf("A stable device identity could not be determined; backup was rejected"),
    "无法读取" to listOf("Could not read"),
    "无法读取云端文件" to listOf("Could not read the cloud file"),
    "无法读取对方发送的内容；请让对方重新选择并发送" to listOf("Could not read what the other device sent. Ask it to select and send again."),
    "无法读取所选图片" to listOf("Could not read the selected image"),
    "无法读取文本" to listOf("Could not read the text"),
    "无法读取源文件；文件可能已移动、删除或访问权限已失效，请重新选择" to listOf("Could not read the source file. It may have been moved, deleted, or access may have expired. Choose it again."),
    "无法读取附件" to listOf("Could not read the attachment"),
    "无法连接对方设备。请确认两台设备在同一局域网、对方传输站仍在运行，并检查系统防火墙或路由器设备隔离。" to listOf("Could not connect to the other device. Confirm both devices are on the same network and the transfer station is running, and check the firewall or router isolation settings."),
    "无法隐藏图片查看缓存" to listOf("Could not hide the image viewer cache"),
    "无账号" to listOf("No account"),
    "无关联包名" to listOf("No linked package"),
    "空" to listOf("Empty"),
    "已设置" to listOf("Set"),
    "内容一致" to listOf("Contents match"),
    "旧格式" to listOf("Legacy format"),
    "旧格式不支持云同步预览" to listOf("Cloud sync preview is not supported for the legacy format"),
    "旧格式云端同步已移除，仅支持 PMVE" to listOf("Legacy cloud sync was removed; only PMVE is supported"),
    "旧格式内联媒体已不支持，仅支持 PMVE 媒体引用" to listOf("Legacy inline media is no longer supported; only PMVE media references are allowed"),
    "旧格式局域网同步已移除，仅支持 PMVE" to listOf("Legacy local network sync was removed; only PMVE is supported"),
    "暂未排除任何应用或网站" to listOf("No apps or websites are excluded"),
    "PC程序排除（随保险库同步）" to listOf("Excluded PC programs (synced with vault)"),
    "更换备份目录" to listOf("Change backup folder"),
    "最多添加 2 张照片" to listOf("A maximum of 2 photos can be added"),
    "服务商写入后仍返回旧版本，系统已多次回读确认；请等待云盘完成发布后重试" to listOf("The provider still returns the old version after writes, confirmed by repeated read-backs. Wait for the cloud drive to finish publishing and try again."),
    "新增" to listOf("Added"),
    "取远端" to listOf("From remote"),
    "留本地" to listOf("Kept local"),
    "保留双份" to listOf("Kept both"),
    "无变化" to listOf("Unchanged"),
    "已清理" to listOf("Cleaned"),
    "忽略过期删除日志" to listOf("Ignored stale deletions"),
    "合并重复条目" to listOf("Merged duplicates"),
    "双方内容一致，未发现需要合并的修改。" to listOf("Both sides match; no changes to merge were found."),
    "已完成拉取、合并、上传和远端读回校验。" to listOf("Pull, merge, upload and remote read-back verification are complete."),
    "已完成拉取和合并；远端已包含合并结果，无需重复上传。" to listOf("Pull and merge are complete; the remote already has the merged result, so no re-upload is needed."),
    "主密码/密钥已在同步中更新，本端已自动采用最新版本。\n\n确认后将锁定保险库，请使用最新主密码重新解锁。" to listOf("The master password or key was updated during sync and this device adopted the latest version automatically.\n\nConfirming locks the vault; unlock it with the new master password."),
    "• 保留本端版本：两端统一使用本端密钥版本\n• 采用远端版本：两端统一使用远端密钥版本\n\n选择后立即执行同步并推送至对方设备。" to listOf("• Keep local version: both sides use the local key version\n• Use remote version: both sides use the remote key version\n\nSyncing starts immediately and pushes to the other device."),
    "局域网" to listOf("Local network"),
    "局域网传输速度较慢，是否继续传输大文件？" to listOf("Local network transfers are slow. Continue with a large file?"),
    "已下载并验证远端保险库，本地文件已原子替换" to listOf("The remote vault was downloaded and verified; the local file was replaced atomically"),
    "已从 WebDAV 下载并验证保险库，本地文件已原子替换" to listOf("The WebDAV vault was downloaded and verified; the local file was replaced atomically"),
    "已允许本次发送，正在等待另一台设备接收" to listOf("Send approved. Waiting for the other device to receive."),
    "已允许本次同步" to listOf("Sync approved"),
    "已允许本次文件传输" to listOf("File transfer approved"),
    "无法完成设备授权，请重新连接" to listOf("Device authorization failed. Reconnect and try again."),
    "当前保险库格式不支持设备确认传输" to listOf("This vault format does not support device-confirmed transfers."),
    "已关闭" to listOf("Closed"),
    "已发送" to listOf("Sent"),
    "已取消" to listOf("Cancelled"),
    "已取消导入" to listOf("Import cancelled"),
    "已取消接收" to listOf("Receiving cancelled"),
    "已复制图片，可粘贴到图库或聊天" to listOf("Image copied. Paste it into Gallery or a chat."),
    "已拒绝同步请求并断开连接" to listOf("Sync request rejected and connection closed"),
    "已拒绝请求并断开连接" to listOf("Request rejected and connection closed"),
    "已接收" to listOf("Received"),
    "已断开" to listOf("Disconnected"),
    "已识别二维码内嵌 PIN，自动连接" to listOf("PIN detected in the QR code; connecting automatically"),
    "已选择备份目录，正在执行首次备份…" to listOf("Backup folder selected. Running the first backup…"),
    "已锁定" to listOf("Locked"),
    "应用包名/网址" to listOf("Package name / website"),
    "建立传输站，或扫码/手动连接进行同步与文件互传" to listOf("Start a transfer station, or scan / connect manually to sync and transfer files"),
    "开启" to listOf("Enable"),
    "开启传输站" to listOf("Start transfer station"),
    "开启后本机将在局域网开放连接，其他设备扫码或手动输入地址和 PIN 后可同步保险库或互传文件。" to listOf("This device opens a local network connection. Other devices can scan the QR code or enter the address and PIN to sync the vault or transfer files."),
    "开启后本机将在局域网开放连接，其他设备扫码或输入地址与 PIN 后，按对方的连接类型执行同步、文件互传或导出确认。" to listOf("This device opens a local network connection. Other devices scan or enter the address and PIN, and the matching action, such as sync, file transfer or export confirmation, starts automatically."),
    "开始传输" to listOf("Start transfer"),
    "开始同步" to listOf("Start sync"),
    "收到的数据不完整" to listOf("The received data is incomplete"),
    "收到的数据不完整，为保护账户已停止接收，请重新连接后再试" to listOf("The received data is incomplete. To protect the vault, receiving was stopped. Reconnect and try again."),
    "文件已写入；已按远端修改时间和大小确认，不再下载解密校验" to listOf("File written; confirmed by remote modification time and size, so no download or decrypt check was needed"),
    "无法确认登录页面来源" to listOf("Could not confirm the login page source"),
    "正在上传并校验云端保险库文件…" to listOf("Uploading and verifying the cloud vault file…"),
    "正在下载并校验云端保险库文件…" to listOf("Downloading and verifying the cloud vault file…"),
    "处理失败：" to listOf("Processing failed: "),
    "扫描识别失败：" to listOf("Scan recognition failed: "),
    "图片处理失败：" to listOf("Image processing failed: "),
    "附件处理失败：" to listOf("Attachment processing failed: "),
    "正在获取动态码…" to listOf("Fetching code…"),
    "继续创建" to listOf("Continue"),
    "确认退出" to listOf("Exit"),
    "退出后需要重新发起通行密钥创建。" to listOf("The passkey creation will restart."),
    "复制代码" to listOf("Copy code"),
    "开启后只允许60bit及以上强度密码" to listOf("Only ≥60-bit master passwords when enabled."),
    "加载中…" to listOf("Loading…"),
    "没有匹配内容" to listOf("No matches"),
    "搜索" to listOf("Search"),
    "改用" to listOf("Use new"),
    "关联域名" to listOf("Linked domain"),
    "街道地址" to listOf("Street address"),
    "自定义敏感文本" to listOf("Custom secret"),
    "自动填充来源冲突" to listOf("Autofill conflict"),
    "此登录条目已关联独立的动态码条目。添加动态码模块后将改用模块中的密钥，并自动解除外部关联。" to listOf("This login is linked to a separate OTP entry. Adding an OTP module uses its key and unlinks the external code."),
    "覆盖并解除关联" to listOf("Override & unlink"),
    "今天" to listOf("Today"),
    "确定" to listOf("OK"),
    "替换外部动态码" to listOf("Replace external OTP"),
    "允许截屏" to listOf("Allow screenshots"),
)

internal val UI_DYNAMIC_EXTRA: List<Pair<Regex, List<String>>> = listOf(
    Regex("^发现时间：(.+)$") to listOf("Detected: $1"),
    Regex("^状态：(.*)$") to listOf("Status: $1"),
    Regex("^连续失败：(\\d+) 次$") to listOf("Consecutive failures: $1"),
    Regex("^已启用 · 上次备份 (.+)$") to listOf("Enabled · last backup $1"),
    Regex("^备份已写入，但备份状态未能保存：(.+)$") to listOf("The backup was written, but its backup state could not be saved: $1"),
    Regex("^创建设备授权请求失败：(.+)$") to listOf("Could not create the device authorization request: $1"),
    Regex("^批准 Passkey 使用权失败：(.+)$") to listOf("Could not approve Passkey access: $1"),
    Regex("^接收 Passkey 使用权失败：(.+)$") to listOf("Could not accept Passkey access: $1"),
    Regex("^授权失败：(.+)$") to listOf("Authorization failed: $1"),
    Regex("^第 (\\d+) 组$") to listOf("Group $1"),
    Regex("^(.+)同步失败$") to listOf("$1 sync failed"),
    Regex("^(\\d+) 组$") to listOf("$1 groups"),
    Regex("^(\\d+) 项$") to listOf("$1 items"),
    Regex("^同步完成 · 更新 (\\d+) 项$") to listOf("Sync complete · $1 items updated"),
    Regex("^正在同步到 (.+)…$") to listOf("Syncing to $1…"),
    Regex("^跳过 (\\d+)$") to listOf("$1 skipped"),
    Regex("^新增 (\\d+)$") to listOf("$1 added"),
    Regex("^更新 (\\d+)$") to listOf("$1 updated"),
    Regex("^冲突 (\\d+)$") to listOf("$1 conflicts"),
    Regex("^请先关联(.+)，再启用自动同步$") to listOf("Connect $1 before enabling automatic sync"),
    Regex("^请先关联(.+)$") to listOf("Connect $1 first"),
    Regex("^同步被拒绝：(.+)。请在两端打开同一账户，或先用数据导入复制完整账户。$") to listOf("Sync rejected: $1. Open the same vault on both devices, or use data import to copy the full vault first."),
    Regex("^同步被拒绝：两端不是同一份保险库，保险库 ID 不一致。为防止跨账户数据混合，接收方未保存任何内容；请在两端打开同一账户，或先用数据导入复制完整账户。$") to listOf("Sync rejected: the two vaults are not the same, vault ID mismatch. To prevent cross-account mixing, nothing was saved on the receiving side. Open the same vault on both devices, or use data import to copy the full vault first."),
    Regex("^同步被拒绝：两端不是同一份保险库，保险库 ID 不一致。请在两端打开同一账户，或先通过数据导入复制完整账户后再同步。$") to listOf("Sync rejected: the two vaults are not the same, vault ID mismatch. Open the same vault on both devices, or use data import to copy the full vault before syncing."),
    Regex("^同步被拒绝：两端保险库提交身份或版本谱系无效；本机数据未修改，请重新建立传输站并确认两端账户。$") to listOf("Sync rejected: invalid commit identity or lineage. Local data was not modified. Recreate the transfer station and confirm both accounts."),
    Regex("^同步被拒绝：两端保险库格式不一致。请先在两端完成格式升级后重试。$") to listOf("Sync rejected: the two vault formats differ. Upgrade both vaults and try again."),
    Regex("^同步被拒绝：对方保险库未通过本机密钥认证，可能选错账户、密钥不同或文件已损坏；本机数据未修改。$") to listOf("Sync rejected: the other vault failed key authentication. The account may be wrong, the key may differ, or the file may be damaged. Local data was not modified."),
    Regex("^同步被拒绝：对方保险库格式与本机不一致。请先在两端完成保险库格式升级后重试。$") to listOf("Sync rejected: the other vault format differs. Upgrade both vaults and try again."),
    Regex("^同步请求被拒绝：(.+)$") to listOf("Sync request rejected: $1"),
    Regex("^同步已暂停 · (.+) · 点击处理$") to listOf("Sync paused · $1 · Tap to resolve"),
    Regex("^传输站已停止：(.+)$") to listOf("Transfer station stopped: $1"),
    Regex("^传输目录：(.+)$") to listOf("Transfer folder: $1"),
    Regex("^云端提供程序返回：(.+)$") to listOf("Cloud provider returned: $1"),
    Regex("^远端文件下载失败：(.+)$") to listOf("Failed to download the remote file: $1"),
    Regex("^验证错误：(.+) 不正确，请重新核对$") to listOf("Verification error: $1 is incorrect. Check it again."),
    Regex("^账户「(.+)」已接收完成，请使用原设备上的主密码解锁$") to listOf("Vault “$1” was received. Unlock it with the master password from the original device."),
    Regex("^本机已有名为“(.+)”的其他保险库。$") to listOf("Another vault named “$1” already exists."),
    Regex("^收到的“(.+)”与本机“(.+)”属于同一份保险库。$") to listOf("The incoming “$1” is the same vault as this device's “$2”."),
    Regex("^如继续，将作为“(.+)”单独导入；不会覆盖现有账户。$") to listOf("If you continue, it will be imported separately as “$1” without overwriting the existing vault."),
    Regex("^你可以重新接收第 (\\d+)/(\\d+) 次，另一台设备上的数据不会受到影响。$") to listOf("You can receive it again, attempt $1/$2; data on the other device is unaffected."),
    Regex("^数据检查未通过，正在自动重试 (.+)/(.+)…$") to listOf("Data check failed; retrying automatically $1/$2…"),
    Regex("^数据检查未通过，正在自动重试 (.+)/(.+)$") to listOf("Data check failed; retrying automatically $1/$2"),
    Regex("^文件检查未通过，正在自动重试 (.+)/(.+)$") to listOf("File check failed; retrying automatically $1/$2"),
    Regex("^正在传输 (\\d+) 项 · (.+)%$") to listOf("Transferring $1 items · $2%"),
    Regex("^正在传输 · (.+)%$") to listOf("Transferring · $1%"),
    Regex("^本地已保存合并结果，但未能上传到云端。(.+)$") to listOf("The merged result was saved locally but could not be uploaded: $1"),
    Regex("^本地提交 #(\\d+)，密钥 v(\\d+)$") to listOf("Local commit #$1, key v$2"),
    Regex("^远端提交 #(\\d+)，密钥 v(\\d+)$") to listOf("Remote commit #$1, key v$2"),
    Regex("^远端数据刚刚更新，正在自动重试 (.+)/(.+)…$") to listOf("Remote data just changed; retrying automatically $1/$2…"),
    Regex("^远端数据刚刚更新，正在重新下载并合并 (.+)/(.+)…$") to listOf("Remote data just changed; downloading and merging again $1/$2…"),
    Regex("^本地数据刚刚更新，正在重新下载并合并 (.+)/(.+)…$") to listOf("Local data just changed; downloading and merging again $1/$2…"),
    Regex("^正在上传并校验 (.+) 远端文件…$") to listOf("Uploading and verifying the $1 remote file…"),
    Regex("^正在下载并校验 (.+) 远端文件…$") to listOf("Downloading and verifying the $1 remote file…"),
    Regex("^包名：(.+) · 密码：空$") to listOf("Package: $1 · Password: empty"),
    Regex("^包名：(.+) · 密码：已设置$") to listOf("Package: $1 · Password: set"),
    Regex("^内部存储/Download/Vaultshare/(.+)$") to listOf("Internal storage/Download/Vaultshare/$1"),
    Regex("^应用存储/Download/Vaultshare/(.+)$") to listOf("App storage/Download/Vaultshare/$1"),
    Regex("^上传远端：成功 · 读回校验：未执行$") to listOf("Remote upload: successful · Read-back verification: not run"),
    Regex("^上传远端：未执行，内容一致 · 远端内容校验：通过$") to listOf("Remote upload: not needed, contents match · Remote verification: passed"),
    Regex("^可用存储空间不足 (\\d+) MB，无法暂存附件$") to listOf("Not enough free space $1 MB to stage the attachment"),
    Regex("^累计提交达 (\\d+) 次且文件增长超过 1 MB 时自动压缩$") to listOf("Automatically compacts after $1 commits and file growth over 1 MB"),
    Regex("^上次清理：临时文件 (\\d+) 个，(.+)$") to listOf("Last cleanup: $1 temporary files, $2"),
    Regex("^保存恢复单失败：(.+)$") to listOf("Could not save the recovery sheet: $1"),
    Regex("^恢复密钥更新失败：(.+)$") to listOf("Could not update the recovery key: $1"),
    Regex("^密码重置失败：(.+)$") to listOf("Password reset failed: $1"),
    Regex("^备份失败：(.+)$") to listOf("Backup failed: $1"),
    Regex("^发送失败：(.+)$") to listOf("Send failed: $1"),
    Regex("^接收失败：(.+)$") to listOf("Receive failed: $1"),
    Regex("^接收同步数据失败：(.+)$") to listOf("Failed to receive sync data: $1"),
    Regex("^文件已保存，但发送端确认失败：(.+)$") to listOf("File saved, but the sender could not confirm: $1"),
    Regex("^图像解码失败：(.+)$") to listOf("Could not decode the image: $1"),
    Regex("^图像预览失败：(.+)$") to listOf("Could not preview the image: $1"),
    Regex("^无法确认 WebDAV 远端仍是已下载版本：(.+)$") to listOf("Could not confirm the WebDAV remote still matches the downloaded version: $1"),
    Regex("^无法确认远端仍是已下载版本：(.+)$") to listOf("Could not confirm the remote still matches the downloaded version: $1"),
    Regex("^远端文件无法认证或已损坏：(.+)$") to listOf("The remote file could not be authenticated or is damaged: $1"),
    Regex("^远端文件元数据多次校验失败：(.+)$") to listOf("Remote file metadata failed verification repeatedly: $1"),
    Regex("^无法启动传输站：(.+)$") to listOf("Could not start the transfer station: $1"),
    Regex("^无法启动传输站：端口 (\\d+) 已被占用，请先关闭占用该端口的程序$") to listOf("Could not start the transfer station: port $1 is already in use. Close the program using it first."),
    Regex("^修改主密码失败：(.+)$") to listOf("Could not change the master password: $1"),
    Regex("^下载覆盖失败，本地数据已保留：(.+)$") to listOf("Download failed; local data was kept: $1"),
    Regex("^云端上传失败：(.+)$") to listOf("Cloud upload failed: $1"),
    Regex("^写入云端硬盘失败：(.+)$") to listOf("Could not write to Cloud Drive: $1"),
    Regex("^创建云端文件失败：(.+)$") to listOf("Could not create the cloud file: $1"),
    Regex("^局域网同步失败：(.+)$") to listOf("Local network sync failed: $1"),
    Regex("^密码管理器数据导入失败：(.+)$") to listOf("Password manager import failed: $1"),
    Regex("^数据库清理失败：(.+)$") to listOf("Database cleanup failed: $1"),
    Regex("^操作失败：(.+)$") to listOf("Operation failed: $1"),
    Regex("^对方已同步：已采纳对方新版本 (\\d+) 项$") to listOf("Other side synced: adopted the other side's new version, $1 items"),
    Regex("^对方已同步：新增 (\\d+)，更新 (\\d+)，一致 (\\d+)$") to listOf("Other side synced: $1 added, $2 updated, $3 identical"),
    Regex("^同步前本地 (\\d+) 项 · 同步后 (\\d+) 项 · 远端 (\\d+) KB$") to listOf("Local before sync: $1 · After sync: $2 · Remote: $3 KB"),
    Regex("^同步前本地 (\\d+) 项 · 同步后 (\\d+) 项$") to listOf("Local before sync: $1 · After sync: $2"),
    Regex("^主密码错误，还可尝试 (\\d+) 次$") to listOf("Incorrect master password. $1 attempts remaining."),
    Regex("^失败次数过多，已锁定 (\\d+) 秒$") to listOf("Too many failed attempts. Unlocking is disabled for $1 seconds."),
    Regex("^尝试次数过多，请等待约 (\\d+) 秒后重试$") to listOf("Too many attempts. Try again in about $1 seconds."),
    Regex("^已同步 · (.+)$") to listOf("Synced · $1"),
    Regex("^已同步并通过安全校验 · (.+)$") to listOf("Synced and verified · $1"),
    Regex("^已删除 (\\d+) 条$") to listOf("$1 deleted"),
    Regex("^已彻底删除 (\\d+) 条$") to listOf("$1 permanently deleted"),
    Regex("^已恢复 (\\d+) 条$") to listOf("$1 restored"),
    Regex("^已排除 (\\d+) 项，点击管理$") to listOf("$1 excluded · Tap to manage"),
    Regex("^已接收 (\\d+)%$") to listOf("Received $1%"),
    Regex("^已新增「(.+)」$") to listOf("Added “$1”"),
    Regex("^已保存「(.+)」$") to listOf("Saved “$1”"),
    Regex("^已删除「(.+)」$") to listOf("Deleted “$1”"),
    Regex("^已彻底删除「(.+)」$") to listOf("Permanently deleted “$1”"),
    Regex("^已恢复「(.+)」$") to listOf("Restored “$1”"),
    Regex("^已重命名为「(.+)」$") to listOf("Renamed to “$1”"),
    Regex("^已导入到账户「(.+)」$") to listOf("Imported into “$1”"),
Regex("^已恢复并导入到账户「(.+)」$") to listOf("Restored and imported into “$1”"),
Regex("^导入失败：(.+)$") to listOf("Import failed: $1"),
    Regex("^已清空回收站 (\\d+) 条$") to listOf("Trash emptied, $1 items"),
    Regex("^已覆盖(.+)远端文件；已按修改时间和大小确认$") to listOf("Overwrote the $1 remote file; confirmed by modification time and size"),
    Regex("^已重命名 (\\d+) 条$") to listOf("$1 renamed"),
    Regex("^已为 (\\d+) 条(.+)标签「(.+)」$") to listOf("Applied the “$3” tag to $1 items"),
    Regex("^自动同步周期 · (.+) · (.+)$") to listOf("Automatic sync interval · $1 · $2"),
    Regex("^上传后多次回读仍未得到本次提交：(.+)$") to listOf("The upload was not confirmed by repeated read-backs: $1"),
    Regex("^WebDAV 上传后多次回读仍未得到本次提交：(.+)$") to listOf("The WebDAV upload was not confirmed by repeated read-backs: $1"),
    Regex("^自动填充排除项保存失败：(.+)$") to listOf("Could not save autofill exclusions: $1"),
    Regex("^保险库维护保存失败：(.+)$") to listOf("Could not save vault maintenance: $1"),
    Regex("^保存失败: (.+)$") to listOf("Save failed: $1"),
    Regex("^发送文件失败：(.+)$") to listOf("Failed to send file: $1"),
    Regex("^发送文本失败：(.+)$") to listOf("Failed to send text: $1"),
    Regex("^(.+)同步失败 · 请重试$") to listOf("$1 sync failed · try again"),
    Regex("^(.+) 超过 1 TB 单文件理论上限$") to listOf("$1 exceeds the 1 TB single-file theoretical limit"),
    Regex("^已同步 · (.+) · 更新 (\\d+) 项 · 已更新云端$") to listOf("Synced · $1 · $2 items updated · Cloud updated"),
    Regex("^已同步并通过安全校验 · (.+) · 更新 (\\d+) 项 · 已更新云端$") to listOf("Synced and verified · $1 · $2 items updated · Cloud updated"),
    Regex("^已同步 · (.+) · 已更新云端$") to listOf("Synced · $1 · Cloud updated"),
    Regex("^已同步并通过安全校验 · (.+) · 已更新云端$") to listOf("Synced and verified · $1 · Cloud updated"),
    Regex("^已同步 · (.+) · 更新 (\\d+) 项$") to listOf("Synced · $1 · $2 items updated"),
    Regex("^已同步并通过安全校验 · (.+) · 更新 (\\d+) 项$") to listOf("Synced and verified · $1 · $2 items updated"),
    Regex("^压缩包导出失败：(.+)$") to listOf("Archive export failed: $1"),
    Regex("^压缩包已导出 (\\d+) 条，(\\d+) 个媒体$") to listOf("Archive exported, $1 items, $2 media files"),
    Regex("^同步失败：(.+)$") to listOf("Sync failed: $1"),
    Regex("^备份周期：(.+)$") to listOf("Backup interval: $1"),
    Regex("^复制图片失败：(.+)$") to listOf("Failed to copy the image: $1"),
    Regex("^新建保险库失败：(.+)$") to listOf("Failed to create the vault: $1"),
    Regex("^无法检查云端文件：(.+)$") to listOf("Could not check the cloud file: $1"),
    Regex("^无法检查云端目录：(.+)$") to listOf("Could not check the cloud folder: $1"),
    Regex("^重新生成失败，旧密钥仍有效：(.+)$") to listOf("Regeneration failed; the old key remains valid: $1"),
    Regex("^上次清理：临时文件 (\\d+) 个，(.+)，压缩回收 (.+)，(.+) → (.+)$") to
        listOf("Last cleanup: $1 temp files, $2, compression reclaimed $3, $4 → $5"),
    Regex("^正在执行 (\\d+) 项后台任务$") to listOf("Running $1 background tasks"),
    Regex("^另有 (\\d+) 项任务进行中$") to listOf("$1 more task(s) in progress"),
    Regex("^(.+)同步$") to listOf("$1 sync"),
    Regex("^正在上传并校验云端保险库文件…$") to listOf("Uploading and verifying the cloud vault file…"),
    Regex("^正在下载并校验云端保险库文件…$") to listOf("Downloading and verifying the cloud vault file…"),
    Regex("^正在同步保险库或传输文件$") to listOf("Syncing the vault or transferring files"),
    Regex("^已从 (.+) 下载并验证保险库，本地文件已原子替换$") to listOf("Downloaded and verified the vault from $1; the local file was replaced atomically"),
    Regex("^已检查 (\\d+) 个条目，发现 (\\d+) 个存在泄露风险$") to listOf("Checked $1 items; $2 at risk of breach"),
    Regex("^已检查 (\\d+) 个条目，未发现泄露$") to listOf("Checked $1 items; no breaches found"),
    Regex("^密码泄露检测失败：(.+)$") to listOf("Breach check failed: $1"),
    Regex("^下载更新失败：(.+)$") to listOf("Update download failed: $1"),
    Regex("^(.+)。导入文件含明文密码，请确认后安全删除$") to listOf("$1. The import file contains plaintext passwords; delete it securely after confirming the import."),
    Regex("^已传输 (.+) / (.+)$") to listOf("Transferred $1 / $2"),
    Regex("^(\\d+) 年$") to listOf("$1 years"),
    Regex("^已选 (\\d+) 条$") to listOf("$1 selected"),
)

internal val UI_COPY_SETTINGS: Map<String, List<String>> = mapOf(
    "● 已连接设备" to listOf("● Connected device"),
    "本地备份" to listOf("Local backup"),
    "本地有新版本，可上传" to listOf("A new local version is available to upload"),
    "标准（推荐）" to listOf("Standard (recommended)"),
    "不是我，断开" to listOf("Not me — disconnect"),
    "传输记录" to listOf("Transfer history"),
    "传输站地址" to listOf("Transfer station address"),
    "此备份包含 Passkey。导出口令至少 14 位并包含大小写字母、数字、符号中的三类。" to listOf("This backup contains Passkeys. The export password must be at least 14 characters and include three of: uppercase, lowercase, digits, symbols."),
    "当前保险库 KDF 等级低于目标，解锁后将自动升级。" to listOf("The vault's current KDF level is below the target; it will be upgraded automatically after unlocking."),
    "当前保险库 KDF 等级已符合目标。" to listOf("The vault's current KDF level already meets the target."),
    "当前保险库参数不被支持。" to listOf("The vault's current parameters are not supported."),
    "导出口令至少 14 位并包含大小写字母、数字、符号中的三类。" to listOf("The export password must be at least 14 characters and include three of: uppercase, lowercase, digits, symbols."),
    "地址未包含有效 PIN，请粘贴传输站的完整地址" to listOf("The address does not contain a valid PIN. Paste the full transfer-station address."),
    "地址已复制，可粘贴到另一台设备" to listOf("Address copied; you can paste it on the other device."),
    "等待其他设备扫码连接" to listOf("Waiting for another device to scan and connect"),
    "定期把保险库文件备份到本机目录或外接U盘/硬盘" to listOf("Periodically back up the vault file to a local directory or external USB drive/disk"),
    "发送" to listOf("Send"),
    "发送内容" to listOf("Content to send"),
    "发送文件" to listOf("Send file"),
    "根据设备性能推荐" to listOf("Recommended based on device performance"),
    "更高内存与迭代，离线破解成本显著增加，解锁稍慢。" to listOf("Higher memory and iterations greatly increase offline cracking cost but unlocking is slightly slower."),
    "更换备份目录" to listOf("Change backup directory"),
    "更新包已下载并开始安装" to listOf("Update package downloaded and installation started"),
    "管理排除项" to listOf("Manage exclusions"),
    "后台界面隐藏" to listOf("Hide background UI"),
    "继续传输" to listOf("Continue transfer"),
    "继续后将立即开始传输，本次会话不再提示。" to listOf("After continuing, the transfer starts immediately and will not prompt again this session."),
    "旧格式不支持云同步预览" to listOf("The old format does not support cloud sync preview"),
    "局域网传输速度较慢，是否继续传输大文件？" to listOf("LAN transfer is slow. Continue transferring large files?"),
    "开启后本机将在局域网开放连接，其他设备扫码或输入地址与 PIN 后，按对方的连接类型执行同步、文件互传或导出确认。" to listOf("When enabled, this device opens a LAN connection. After another device scans the QR code or enters the address and PIN, it performs sync, file transfer, or export confirmation based on its connection type."),
    "立即备份" to listOf("Back up now"),
    "连接将立即关闭，尚未完成的发送或接收会被中断；已完成的传输记录会保留到离开当前页面。" to listOf("The connection closes immediately; unfinished sends or receives are interrupted. Completed transfer records are kept until you leave the page."),
    "目录不可用或未连接时自动等待，不报错" to listOf("Automatically wait without error when the directory is unavailable or disconnected"),
    "启用本地备份" to listOf("Enable local backup"),
    "强化" to listOf("Strong"),
    "切到后台时从最近任务中隐藏" to listOf("Hide from recent tasks when switched to background"),
    "确认关闭" to listOf("Confirm close"),
    "确认关闭传输站？" to listOf("Confirm closing the transfer station?"),
    "确认结束" to listOf("Confirm end"),
    "让另一台设备扫描上方二维码，或手动输入地址和 PIN 连接" to listOf("Let the other device scan the QR code above, or manually enter the address and PIN to connect"),
    "上传覆盖完成，远端文件已通过读回校验" to listOf("Upload overwrite complete; the remote file passed the read-back verification"),
    "尚未关联" to listOf("Not yet linked"),
    "尚无传输记录" to listOf("No transfer records yet"),
    "输入文本，长按可粘贴剪贴板内容" to listOf("Enter text; long-press to paste from clipboard"),
    "双方均有修改，可自动合并" to listOf("Both sides have changes and can be merged automatically"),
    "私钥随加密保险库同步，新设备打开同一数据库后可直接使用。" to listOf("The private key syncs with the encrypted vault; a new device can use it directly after opening the same database."),
    "添加" to listOf("Add"),
    "添加后，排除的应用或网站将不显示自动填充建议" to listOf("After adding, excluded apps or websites will not show autofill suggestions"),
    "同步型 Passkey 在同步到新设备后即可使用；高安全性模式的私钥只存在于当前设备。" to listOf("Syncable Passkeys work after syncing to a new device; high-security mode keeps the private key only on the current device."),
    "文本超过 1 MB，请作为文件打开" to listOf("Text exceeds 1 MB; please open it as a file"),
    "文件传输连接将立即关闭，尚未完成的发送或接收会被中断。" to listOf("The file-transfer connection closes immediately; unfinished sends or receives are interrupted."),
    "下载覆盖完成，本地文件已通过写入校验" to listOf("Download overwrite complete; the local file passed the write verification"),
    "校准中…" to listOf("Calibrating…"),
    "选择备份目录" to listOf("Choose backup directory"),
    "选择应用" to listOf("Choose app"),
    "移除" to listOf("Remove"),
    "已识别二维码内嵌 PIN，自动连接" to listOf("QR code's embedded PIN recognized; connecting automatically"),
    "应用包名/网址" to listOf("App package name / URL"),
    "应用更新" to listOf("App updates"),
    "远端不是同一份保险库" to listOf("The remote is not the same vault"),
    "远端有新版本，可拉取" to listOf("A new remote version is available to pull"),
    "允许本次发送" to listOf("Allow this send"),
    "允许本次同步" to listOf("Allow this sync"),
    "允许并建立绑定" to listOf("Allow and establish binding"),
    "允许此存储设备用于同步" to listOf("Allow this storage device for sync"),
    "暂未排除任何应用或网站" to listOf("No apps or websites excluded yet"),
    "正在下载更新包…" to listOf("Downloading update package…"),
    "正在验证 WebDAV 连接，请稍候…" to listOf("Verifying the WebDAV connection, please wait…"),
    "自动填充排除" to listOf("Autofill exclusions"),
    "Argon2id 参数越高，离线暴力破解成本越高，但解锁与重设密码越慢。" to listOf("Higher Argon2id parameters increase offline brute-force cost but make unlocking and password reset slower."),
    "Argon2id 内存 64 MiB、迭代 3、并行 1，兼顾解锁速度与抗破解。" to listOf("Argon2id with 64 MiB memory, 3 iterations, 1 parallelism balances unlock speed and cracking resistance."),
    "FAEVault 将在所选目录写入设备 UUID，并把它与本次系统目录授权绑定。只有两项身份都匹配时才会自动同步；设备疑似变化时需要再次确认。" to listOf("FAEVault writes a device UUID into the chosen directory and binds it to this system directory authorization. Auto-sync happens only when both identities match; a suspected device change requires re-confirmation."),
    "KDF 安全等级" to listOf("KDF security level"),
    "允许截屏？" to listOf("Allow screenshots?"),
    "开启后，保险库内容可能出现在截图、录屏、投屏画面和最近任务预览中。恶意应用或他人也可能保存敏感信息。仅在确有需要且环境可信时开启。" to listOf("When enabled, vault contents may appear in screenshots, screen recordings, cast screens, and recent-task previews. Malicious apps or other people could save sensitive information. Only enable this when needed and in a trusted environment."),
    "我已了解风险，仍要允许" to listOf("I understand the risks; allow anyway"),
    "保持禁止" to listOf("Keep blocking"),
    "允许截屏会使保险库内容暴露在截图、录屏和投屏中，需要验证当前主密码。" to listOf("Allowing screenshots can expose vault contents in screenshots, recordings, and cast screens. Verify the current master password."),
    "当前不允许系统截图、录屏和大多数投屏捕获。" to listOf("System screenshots, recordings, and most casting captures are currently not allowed."),
    "已允许系统截图和录屏；敏感内容可能被其他应用或旁观者保存。" to listOf("System screenshots and recordings are allowed; other apps or people may save sensitive content."),
)
