package com.vault.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalConfiguration

/** Semantic UI copy shared by Compose screens that are being migrated from literals. */
internal fun localizeUiText(source: String, languageTag: String): String {
    if (!languageTag.startsWith("en", true)) return source
    UI_COPY[source]?.get(0)?.let { return it }
    UI_COPY_EXTRA[source]?.get(0)?.let { return it }
    UI_COPY_SETTINGS[source]?.get(0)?.let { return it }
    UI_DYNAMIC.forEach { (pattern, replacements) ->
        if (pattern.matches(source)) return pattern.replace(source, replacements[0])
    }
    UI_DYNAMIC_EXTRA.forEach { (pattern, replacements) ->
        if (pattern.matches(source)) return pattern.replace(source, replacements[0])
    }
    return source
}

/** Only generated fallback volume labels are translated; user-defined names remain untouched. */
internal fun localizeBackupDeviceLabel(source: String, languageTag: String): String {
    val match = Regex("^(.+?)[（(](VOL-[A-Za-z0-9]+)[）)](.*)$").matchEntire(source)
        ?: return localizeUiText(source, languageTag)
    val canonical = when (match.groupValues[1]) {
        "备份设备", "Backup device" -> "备份设备"
        "本机存储", "Local storage" -> "本机存储"
        else -> return source
    }
    val english = languageTag.startsWith("en", true)
    val name = localizeUiText(canonical, languageTag)
    return name + (if (english) "(" else "（") + match.groupValues[2] +
        (if (english) ")" else "）") + match.groupValues[3]
}

/** Persisted sync messages can contain independently localized status and error segments. */
internal fun localizeCloudSyncStatus(source: String, languageTag: String): String {
    if (!languageTag.startsWith("en", true)) return source
    val match = Regex("^(自动同步失败|自动同步已暂停)[：:]\\s*(.+)$").matchEntire(source)
        ?: return localizeUiText(source, languageTag)
    return localizeUiText(match.groupValues[1], languageTag) + ": " +
        localizeUiText(match.groupValues[2], languageTag)
}

@Composable
internal fun uiBackupDeviceLabel(source: String): String =
    localizeBackupDeviceLabel(source, LocalConfiguration.current.locales[0].toLanguageTag())

@Composable
internal fun uiCloudSyncStatus(source: String): String =
    localizeCloudSyncStatus(source, LocalConfiguration.current.locales[0].toLanguageTag())

/** Locale-aware lookup for non-composable contexts (Toast/Notification/Activity callbacks). */
internal fun localizeUiTextFor(context: android.content.Context, source: String): String {
    val locales = context.resources.configuration.locales
    return localizeUiText(source, locales[0].toLanguageTag())
}

@Composable
internal fun uiText(source: String): String {
    // LocalConfiguration 是 Compose 的 snapshot 状态：语言/区域配置变化时（无论是否重建
    // Activity）都会触发读取方重组，避免切换语言后旧文案残留到下一次交互才刷新。
    val locales = LocalConfiguration.current.locales
    return localizeUiText(source, locales[0].toLanguageTag())
}

/**
 * 档位切换按钮的短标签：英文用紧凑短语（Station / LAN sync / Transfer / Cloud drive），
 * 避免完整翻译（如 “Establish transfer station”）在三分/二分等宽段中被截断。
 * 中文保持原文案不变。
 */
private val UI_TAB_COPY = mapOf(
    "建立传输站" to "Station",
    "局域网同步" to "LAN sync",
    "文件传输" to "Transfer",
    "云端硬盘" to "Cloud drive",
)

@Composable
internal fun uiTabText(source: String): String {
    val locales = LocalConfiguration.current.locales
    val tag = locales[0].toLanguageTag()
    if (!tag.startsWith("en", true)) return source
    return UI_TAB_COPY[source] ?: localizeUiText(source, tag)
}

private val UI_COPY = mapOf(
    "检查更新" to listOf("Check for updates"),
    "正在检查…" to listOf("Checking…"),
    "当前已是最新版本" to listOf("You are up to date"),
    "检查更新失败" to listOf("Update check failed"),
    "发现新版本" to listOf("New version available"),
    "此版本未提供更新说明。" to listOf("No release notes were provided for this version."),
    "下载更新" to listOf("Download update"),
    "无法打开下载" to listOf("Could not open the download"),
    "正在下载更新…" to listOf("Downloading update…"),
    "正在校验安装包…" to listOf("Verifying the update…"),
    "正在准备安装…" to listOf("Preparing to install…"),
    "下载更新失败" to listOf("Download failed"),
    "安装包签名与当前版本不一致，已取消安装" to listOf("The update signature does not match the installed app. Installation cancelled."),
    "安装包信息无效" to listOf("Invalid update package"),
    "更新包版本无效" to listOf("The update package version is invalid"),
    "未找到可安装 APK 的应用" to listOf("No app can install this APK"),
    "需要允许安装未知应用后才能安装更新" to listOf("Allow installing unknown apps to install the update"),
    "去开启" to listOf("Enable"),
    "正在打开设置…" to listOf("Opening settings…"),
    "重试" to listOf("Retry"),
    "已开始安装，完成后请重新打开保险库" to listOf("Installation started. Reopen the vault when it finishes."),
    "稍后" to listOf("Later"),
    "已泄露" to listOf("Exposed"),
    "已过期" to listOf("Expired"),
    "即将到期" to listOf("Expiring soon"),
    "密码安全性" to listOf("Password safety"),
    "显示后自动隐藏" to listOf("Hide after revealing"),
    "联系" to listOf("Contact"),
    "赞助支持" to listOf("Support development"),
    "每个保险库都必须包含恢复密钥，不可删除。" to listOf("Every vault must have a recovery key. It cannot be deleted."),
    "解锁时检查回收站，超过设定天数的条目将被自动彻底删除。" to listOf("Trash is checked when the vault unlocks. Items older than the selected period are permanently deleted."),
    "用户名" to listOf("Username"),
    "密码" to listOf("Password"),
    "网址" to listOf("Website"),
    "创建时间" to listOf("Created"),
    "修改" to listOf("Modified"),
    "编辑" to listOf("Edit"),
    "删除" to listOf("Delete"),
    "复制" to listOf("Copy"),
    "账户设置" to listOf("Vault settings"),
    "安全" to listOf("Safe"),
    "安全中心" to listOf("Security"),
    "备份与导出" to listOf("Backup and export"),
    "导入与导出" to listOf("Import and export"),
    "局域网同步" to listOf("Local network sync"),
    "局域网导入" to listOf("Local network import"),
    "扫描二维码导入" to listOf("Scan QR code to import"),
    "手动输入地址与连接码" to listOf("Enter address and code"),
    "发送全部条目" to listOf("Export all items"),
    "选择条目…" to listOf("Choose items…"),
    "从其他设备导入" to listOf("Import from another device"),
    "本机发送到其他设备" to listOf("Export to another device"),
    "选择要导出的条目" to listOf("Choose items to export"),
    "开启导入会话" to listOf("Start import session"),
    "停止导入会话" to listOf("Stop import session"),
    "确认导入" to listOf("Confirm import"),
    "继续" to listOf("Continue"),
    "完成" to listOf("Done"),
    "密码健康" to listOf("Password security"),
    "高风险" to listOf("High risk"),
    "需改进" to listOf("Needs attention"),
    "未发现问题" to listOf("No issues found"),
    "条目名称" to listOf("Item name"),
    "标签" to listOf("Tags"),
    "备注" to listOf("Notes"),
    "附加内容" to listOf("Additional content"),
    "添加模块" to listOf("Add module"),
    "删除模块" to listOf("Delete module"),
    "取消" to listOf("Cancel"),
    "确认" to listOf("Confirm"),
    "保存" to listOf("Save"),
    "新增条目" to listOf("New item"),
    "编辑条目" to listOf("Edit item"),
    "搜索名称、用户名、标签…" to listOf("Search names, usernames or tags…"),
    "公开泄露" to listOf("Found in a known breach"),
    "重复密码" to listOf("Reused password"),
    "强度极低" to listOf("Very weak password"),
    "常见/初始密码" to listOf("Common or default pattern"),
    "建议改进" to listOf("Recommendations"),
    "修改主密码" to listOf("Change master password"),
    "启用生物识别解锁" to listOf("Enable biometric unlock"),
    "关闭生物识别解锁" to listOf("Disable biometric unlock"),
    "导入其他加密数据" to listOf("Import other encrypted data"),
    "同步与数据迁移" to listOf("Sync and data transfer"),
    "云端同步" to listOf("Cloud sync"),
    "紧急恢复密钥" to listOf("Emergency recovery key"),
    "保险库紧急恢复密钥" to listOf("FAEVault Emergency Recovery Key"),
    "保险库恢复密钥" to listOf("FAEVault Recovery Key"),
    "请离线保存，不要与主密码放在一起。" to listOf("Keep this offline and separate from your master password."),
    "保险库维护" to listOf("Vault maintenance"),
    "检测设置" to listOf("Check settings"),
    "高风险检测" to listOf("High-risk findings"),
    "密码安全总览" to listOf("Password security overview"),
    "自动锁定" to listOf("Auto-lock"),
    "回收站自动清理" to listOf("Automatic Trash cleanup"),
    "敏感内容二次保护" to listOf("Sensitive-content protection"),
    "剪贴板自动清理" to listOf("Clean clipboard automatically"),
    "外观" to listOf("Appearance"),
    "关于" to listOf("About"),
    "搜索条目" to listOf("Search items"),
    "选择模块" to listOf("Choose a module"),
    "选择动态码" to listOf("Choose a one-time code"),
    "选择 Wi-Fi 网络" to listOf("Choose a Wi-Fi network"),
    "强制敏感" to listOf("Always sensitive"),
    "敏感模块" to listOf("Sensitive module"),
    "普通模块" to listOf("Standard module"),
    "选择关联应用" to listOf("Select app to associate"),
    "高级选项" to listOf("Advanced options"),
    "需要权限" to listOf("Permission required"),
    "生成" to listOf("Generate"),
    "分享 Wi-Fi 二维码" to listOf("Share Wi-Fi QR code"),
    "分享WiFi" to listOf("Share Wi-Fi"),
    "移入回收站" to listOf("Move to Trash"),
    "Wi-Fi 二维码" to listOf("Wi-Fi QR code"),
    "将移入回收站，可在 30 天内恢复。" to listOf("Will be moved to Trash and can be restored for 30 days."),
    "从相册选取 Wi-Fi 二维码" to listOf("Choose a Wi-Fi QR code from Gallery"),
    "扫码导入" to listOf("Import by scanning"),
    "从相册选取二维码" to listOf("Choose QR code from Gallery"),
    "选择要导入的二维码" to listOf("Choose a QR code to import"),
    "允许" to listOf("Allow"),
    "前往设置" to listOf("Open settings"),
    "识别中…" to listOf("Recognizing…"),
    "正在导入 Wi-Fi…" to listOf("Importing Wi-Fi…"),
    "扫码导入 Wi-Fi" to listOf("Scan to import Wi-Fi"),
    "正在读取当前 Wi-Fi…" to listOf("Reading current Wi-Fi…"),
    "导入当前 Wi-Fi" to listOf("Import current Wi-Fi"),
    "已有标签" to listOf("Existing tags"),
    "需要使用相机权限来扫描二维码和拍摄文档。" to listOf("Camera access is required to scan QR codes and photograph documents."),
    "需要使用相册权限来选取图片。" to listOf("Photo access is required to choose images."),
    "需要使用此权限才能完成操作。" to listOf("This permission is required to complete the action."),
    "未选择" to listOf("Not selected"),
    "无加密" to listOf("Open"),
    "通行密钥数据无效，已停止使用" to listOf("Invalid passkey data; this passkey has been disabled"),
    "通行密钥存在密钥冲突，已停止使用" to listOf("This passkey has a key conflict and has been disabled"),
    "完整卡号" to listOf("Full card number"),
    "取款密码" to listOf("ATM PIN"),
    "证件号" to listOf("Document number"),
    "Wi-Fi 密码" to listOf("Wi-Fi password"),
    "安全笔记内容" to listOf("Secure note"),
    "模块" to listOf("Module"),
    "标题" to listOf("Title"),
    "备注内容" to listOf("Notes"),
    "应用包名" to listOf("App package"),
    "服务名称" to listOf("Service name"),
    "私钥" to listOf("Private key"),
    "数据库名" to listOf("Database"),
    "安全问题" to listOf("Security question"),
    "答案" to listOf("Answer"),
    "最后使用" to listOf("Last used"),
    "签名计数" to listOf("Signature count"),
    "依赖方" to listOf("Relying party"),
    "账户" to listOf("Account"),
    "未知" to listOf("Unknown"),
    "由 Android 通行密钥提供程序创建和使用，密钥材料不可手动编辑。" to listOf("Created and used by the Android passkey provider. Key material cannot be edited manually."),
    "自定义证件名称" to listOf("Custom document name"),
    "请输入证件类型名称" to listOf("Enter a document type"),
    "添加图片" to listOf("Add image"),
    "此模块已有内容，确定删除吗？" to listOf("This module contains data. Delete it?"),
    "当前版本暂不支持此模块；数据将原样保留。" to listOf("This module is not supported in this version. Its data will be preserved."),
    "添加附件" to listOf("Add attachment"),
    "选择已安装程序" to listOf("Choose installed app"),
    "扫码" to listOf("Scan"), "相册" to listOf("Gallery"),
    "扫描" to listOf("Scan"), "使用当前位置" to listOf("Use current location"),
    "文本" to listOf("Text"), "多行文本" to listOf("Multiline text"),
    "图片" to listOf("Images"), "附件" to listOf("Attachments"),
        "登录" to listOf("Login"),
    "关联程序" to listOf("Linked app"),
    "API 凭证" to listOf("API credentials"),
        "服务器" to listOf("Server"),
    "数据库连接" to listOf("Database connection"),
    "动态码" to listOf("One-time code"),
    "关联填充内容" to listOf("Link autofill content"),
    "关联自动填充内容" to listOf("Linked autofill content"),
    "来源不可用" to listOf("Source unavailable"),
    "查看详情" to listOf("View details"),
    "此登录条目已包含动态码模块，不能重复关联" to listOf("This login already has a one-time-code module and cannot link another"),
    "没有可关联的独立动态码条目" to listOf("No standalone one-time-code entry to link"),
    "银行卡" to listOf("Payment card"),
    "卡证" to listOf("Cards & documents"),
    "其他卡证" to listOf("Other card or document"),
    "自定义卡证名称" to listOf("Custom card or document name"),
    "卡片类型" to listOf("Card type"),
    "日期时间类型" to listOf("Date and time type"),
    "日期时间" to listOf("Date and time"),
    "布尔值" to listOf("Boolean"),
    "仅日期" to listOf("Date only"),
    "仅时间" to listOf("Time only"),
    "日期和时间" to listOf("Date and time"),
    "选择日期" to listOf("Choose date"),
    "选择分类" to listOf("Choose a category"),
    "搜索分类" to listOf("Search categories"),
    "以下内容已有来源，请选择保留当前内容或改用新条目：" to listOf("The following content already has a source. Keep the current content or use the new item:"),
    "保留当前内容" to listOf("Keep current content"),
    "日历选择" to listOf("Choose from calendar"),
    "小时" to listOf("Hour"),
    "分钟" to listOf("Minute"),
    "格式无效" to listOf("Invalid format"),
    "是" to listOf("Yes"),
    "否" to listOf("No"),
    "证件" to listOf("Identity document"),
    "拍照识别身份证" to listOf("Scan ID card"),
    "地址" to listOf("Address"), "恢复信息" to listOf("Recovery information"),
    "通用" to listOf("General"), "账号与网络" to listOf("Accounts and network"),
    "身份与金融" to listOf("Identity and finance"),
    "基本信息" to listOf("Basic information"),
    "用于识别和查找此条目" to listOf("Helps identify and find this item"),
    "按需组合模块，长按模块可调整顺序" to listOf("Add only what you need; press and hold a module to reorder it"),
    "补充不属于字段的说明" to listOf("Add information that does not belong in a field"),
    "账号、密码与目标应用" to listOf("Account, password and target app"),
    "卡片信息与卡面影像" to listOf("Card details and images"),
    "证件字段与正反面影像" to listOf("Document details and images"),
    "网络凭据与路由器信息" to listOf("Network credentials and router details"),
    "接口身份与访问密钥" to listOf("API identity and access keys"),
    "动态口令参数" to listOf("One-time-code settings"),
    "受保护的自由文本" to listOf("Protected free-form text"),
    "主机连接与认证信息" to listOf("Host connection and authentication"),
    "自由组合所需内容模块" to listOf("Combine the content modules you need"),
    "类型" to listOf("Type"), "内容" to listOf("Content"),
    "主机 / IP" to listOf("Host / IP"), "端口" to listOf("Port"),
    "加密类型" to listOf("Security type"),
    "路由器管理地址" to listOf("Router admin address"),
    "持卡人" to listOf("Cardholder"), "卡号" to listOf("Card number"),
    "有效期" to listOf("Expiry"), "银行" to listOf("Bank"),
    "姓名" to listOf("Full name"), "证件类型" to listOf("Document type"),
    "证件号码" to listOf("Document number"), "签发日期" to listOf("Issued"),
    "到期日期" to listOf("Expires"), "签发机关" to listOf("Issuing authority"),
    "密钥" to listOf("Secret key"), "发行方" to listOf("Issuer"),
    "账户名" to listOf("Account name"), "算法" to listOf("Algorithm"),
    "位数" to listOf("Digits"), "周期" to listOf("Period"),
    "计数器" to listOf("Counter"),
    "导出加密备份 .pmbak" to listOf("Export encrypted backup .pmbak"),
    "导入加密备份并合并" to listOf("Import and merge encrypted backup"),
    "导出原始 .pmv" to listOf("Export original .pmv"),
    "手动输入地址" to listOf("Enter address manually"),
    "建立传输站" to listOf("Establish transfer station"),
    
    "服务器地址" to listOf("Server address"),
    "PIN 码" to listOf("PIN"), "证书 SHA-256 指纹" to listOf("Certificate SHA-256 fingerprint"), "开始同步" to listOf("Start sync"),
    "正在验证 PIN 码…" to listOf("Verifying PIN…"),
    "PIN 码连续错误 5 次，连接已断开" to listOf("The connection was closed after 5 incorrect PIN attempts."),
    "无法连接对方设备，请确认对方传输站仍然开启" to listOf("Could not connect to the other device. Make sure its transfer station is still open."),
    "启用联网同步" to listOf("Enable online sync"),
    "云端硬盘" to listOf("Cloud drive"),
    "关联云端硬盘" to listOf("Connect cloud drive"),
    "重新检测" to listOf("Check again"), "同步" to listOf("Sync"),
    "上传覆盖云端" to listOf("Overwrite remote vault"),
    "下载覆盖本地" to listOf("Replace local vault"),
    "重新关联" to listOf("Reconnect"), "取消关联" to listOf("Disconnect"),
    "关联 WebDAV" to listOf("Connect WebDAV"),
    "自动同步" to listOf("Automatic sync"),
    "尚未执行自动同步" to listOf("Automatic sync has not run yet"),
    "自动同步完成" to listOf("Automatic sync completed"),
    "自动同步失败" to listOf("Automatic sync failed"),
    "自动同步已暂停" to listOf("Automatic sync paused"),
    "同步正在进行，本次自动同步已跳过" to listOf("Sync is already running; this automatic attempt was skipped"),
    "已删除" to listOf("deleted"),
    "不属于当前保险库" to listOf("wrong vault"),
    "损坏" to listOf("corrupt"),
    "校验失败" to listOf("verification failed"),
    "云端硬盘未关联，自动同步已暂停" to listOf("Cloud Drive is not connected. Automatic sync is paused."),
    "WebDAV未关联，自动同步已暂停" to listOf("WebDAV is not connected. Automatic sync is paused."),
    "15分钟" to listOf("15 minutes"),
    "30分钟" to listOf("30 minutes"),
    "1小时" to listOf("1 hour"),
    "3小时" to listOf("3 hours"),
    "6小时" to listOf("6 hours"),
    "每天" to listOf("Daily"),
    "每周" to listOf("Weekly"),
    "自动云端同步" to listOf("Automatic cloud sync"),
    "自动同步目标" to listOf("Automatic sync target"),
    "恢复密钥泄露/丢失？重新生成" to listOf("Recovery key exposed or lost? Generate a new one"),
    "隐私政策" to listOf("Privacy policy"),
    "更新日志" to listOf("Release notes"),
    "关闭" to listOf("Close"),
    "帮助" to listOf("Help"),
    "代码块" to listOf("Code block"),
    "连接其他设备，或导入导出保险库数据" to listOf("Connect to another device, or import and export vault data"),
    "与对方同步" to listOf("Sync with the other device"),
    "与同一局域网内的其他设备同步密码库" to listOf("Sync the vault with another device on the same local network"),
    "默认关闭，仅在主动操作时连接云端" to listOf("Off by default; connects only when you start an action"),
    "通过系统文件选择器关联云端文件；同步会先拉取合并，再上传并读回校验。" to listOf("Connect a cloud file with the system picker. Sync downloads and merges first, then uploads and verifies the result."),
    "适用于群晖、威联通、Nextcloud、ownCloud 及其他 WebDAV 服务。" to listOf("Works with Synology, QNAP, Nextcloud, ownCloud and other WebDAV services."),
    "仅在保险库解锁期间运行" to listOf("Runs only while the vault is unlocked"),
    "支持 Bitwarden CSV/未加密 JSON，以及 1Password、LastPass、KeePass 和主流浏览器 CSV；导入后与当前库合并。" to listOf("Supports Bitwarden CSV or unencrypted JSON, plus CSV exports from 1Password, LastPass, KeePass and major browsers. Imported items are merged into this vault."),
    "相似密码" to listOf("Similar passwords reused"),
    "长度不足 12 位" to listOf("Fewer than 12 characters"),
    "包含账户信息" to listOf("Contains account information"),
    "长期未修改" to listOf("Not changed for a long time"),
    "该密码已出现在公开泄露数据中。" to listOf("This password appears in public breach data."),
    "多个条目使用了相同密码。" to listOf("Multiple items use the same password."),
    "密码太短或字符种类过少。" to listOf("The password is too short or has too little variety."),
    "立即更换，勿在其他账户复用。" to listOf("Change it now and do not reuse it elsewhere."),
    "为每个账户设置不同的随机密码。" to listOf("Use a different random password for every account."),
    "改用至少 12 位且难以猜测的随机密码。" to listOf("Use a hard-to-guess random password with at least 12 characters."),
    "密码过于常见或存在明显规律。" to listOf("The password is too common or follows an obvious pattern."),
    "更换为随机的强密码。" to listOf("Switch to a strong random password."),
    "多个密码只是在细节上略有不同。" to listOf("Several passwords differ only in minor details."),
    "改用互不相关的密码。" to listOf("Use unrelated passwords instead."),
    "密码长度少于建议的 12 位。" to listOf("The password is shorter than the recommended 12 characters."),
    "换用更长的密码。" to listOf("Switch to a longer password."),
    "密码包含账号、名称或网址中的内容。" to listOf("The password contains account, name, or URL details."),
    "移除与账户资料相关的内容。" to listOf("Remove details that can be guessed from the account."),
    "该条目长期未修改。" to listOf("This item has not been changed for a long time."),
    "确认密码仍然有效且未泄露，必要时更换。" to listOf("Confirm the password is still valid and uncompromised; change it if needed."),
    "合并后标题" to listOf("Merged title"),
    "合并后用户名" to listOf("Merged username"),
    "合并后密码" to listOf("Merged password"),
    "返回修改" to listOf("Back to editing"),
    "未命名条目" to listOf("Untitled item"),
    "无标题" to listOf("Untitled"),
    "回收站为空" to listOf("Trash is empty"),
    "恢复" to listOf("Restore"),
    "全选" to listOf("Select all"),
    "取消全选" to listOf("Clear selection"),
    "取消选择" to listOf("Cancel selection"),
    "清空回收站" to listOf("Empty Trash"),
    "再次确认清空" to listOf("Confirm emptying Trash"),
    "彻底清空" to listOf("Empty permanently"),
    "彻底删除条目" to listOf("Delete item permanently"),
    "彻底删除所选条目" to listOf("Delete selected items permanently"),
    "彻底删除" to listOf("Delete permanently"),
    "下一步" to listOf("Next"),
    "批量移入回收站" to listOf("Move selected items to Trash"),
    "没有匹配的条目" to listOf("No matching items"),
    "搜索应用名或包名" to listOf("Search app name or package"),
    "去设置开启" to listOf("Enable in Settings"),
    "显示" to listOf("Show"),
    "隐藏" to listOf("Hide"),
    "显隐" to listOf("Show or hide"),
    "清除" to listOf("Clear"),
    "导出附件" to listOf("Export attachment"),
    "复制附件校验值" to listOf("Copy attachment checksum"),
    "下载附件" to listOf("Download attachment"),
    "复制动态码" to listOf("Copy one-time code"),
    "附件已导出" to listOf("Attachment exported"),
    "不是有效的 Wi-Fi 二维码" to listOf("This is not a valid Wi-Fi QR code"),
    "已导入 OTP 配置" to listOf("One-time-code settings imported"),
    "未识别到关键字段" to listOf("No key fields were recognized"),
    "图片中没有有效的 Wi-Fi 二维码" to listOf("No valid Wi-Fi QR code was found in the image"),
    "图片中没有有效的 TOTP/HOTP 二维码" to listOf("No valid TOTP or HOTP QR code was found in the image"),
    "不是有效的 otpauth:// 二维码" to listOf("This is not a valid otpauth QR code"),
    "不是有效的 TOTP/HOTP 二维码" to listOf("This is not a valid TOTP or HOTP QR code"),
    "需要相机权限才能使用此功能" to listOf("Camera access is required for this feature"),
    "需要相册权限才能选取图片" to listOf("Photo access is required to choose an image"),
    "无法启动 Google 扫描，请尝试手动拍照后使用 OCR" to listOf("Google scanning could not start. Take a photo manually and use OCR instead."),
    "请输入标题" to listOf("Enter a title"),
    "拍照识别银行卡" to listOf("Scan payment card"),
    "拍照识别证件" to listOf("Scan identity document"),
    "卡号末四位" to listOf("Last four digits"),
    "卡面照片" to listOf("Card images"),
    "有效期 MM/YY" to listOf("Expiry MM/YY"),
    "用户名 / AppId" to listOf("Username / App ID"),
    "Base32 编码" to listOf("Base32 encoded"),
    "无法打开系统设置，请手动前往设置 → 应用管理 → 本应用 → 权限" to listOf("Could not open system settings. Open Settings → Apps → FAEVault → Permissions."),
    "此模块最多保存 8 张图片" to listOf("This module can contain up to 8 images"),
    "每个图片模块最多 8 张" to listOf("Each image module can contain up to 8 images"),
    "每个图片区最多保存 8 张" to listOf("Each image area can contain up to 8 images"),
    "图片数量已达理论上限" to listOf("Image count has reached the theoretical maximum"),
    "附件数量已达理论上限" to listOf("Attachment count has reached the theoretical maximum"),
    "单张图片不能超过 8 MB" to listOf("An image cannot exceed 8 MB"),
    "图片大小超过允许上限" to listOf("The image exceeds the allowed size limit"),
    "图片和附件总容量不能超过 32 MB" to listOf("Images and attachments cannot exceed 32 MB in total"),
    "该图片已存在" to listOf("This image has already been added"),
    "未识别到可填入字段" to listOf("No usable fields were recognized"),
    "无法读取图片" to listOf("Could not read the image"),
    "未知错误" to listOf("Unknown error"),
    "已填入当前位置" to listOf("Current location added"),
    "定位失败" to listOf("Could not determine your location"),
    "未授予所需权限" to listOf("Required permission was not granted"),
    "未授予位置权限" to listOf("Location permission was not granted"),
    "需要使用位置权限来获取当前位置。" to listOf("Location access is required to get the current location."),
    "位置权限已被永久拒绝。请前往系统设置手动授权。" to listOf("Location access was permanently denied. Grant it manually in system settings."),
    "正在获取当前位置…" to listOf("Getting current location…"),
    "添加第一个模块" to listOf("Add the first module"),
    "继续添加模块" to listOf("Add another module"),
    "已达上限" to listOf("Limit reached"),
    "生成强密码" to listOf("Generate a strong password"),
    "密码长度" to listOf("Password length"),
    "包含字符" to listOf("Character types"),
    "避开形近字符" to listOf("Avoid similar characters"),
    "排除 0/O、1/l/I 等易混淆字符" to listOf("Exclude easily confused characters such as 0/O and 1/l/I"),
    "使用此密码" to listOf("Use this password"),
    "大写字母" to listOf("Uppercase"),
    "小写字母" to listOf("Lowercase"),
    "数字" to listOf("Numbers"),
    "符号" to listOf("Symbols"),
    "仅显示一次" to listOf("Shown only once"),
    "复制密钥" to listOf("Copy key"),
    "已复制" to listOf("Copied"),
    "保存恢复单" to listOf("Save recovery sheet"),
    "第 2 步 · 核对已保存内容" to listOf("Step 2 · Verify your saved copy"),
    "密钥内容已隐藏，请从你保存的位置参考。" to listOf("The key is hidden. Refer to the copy you saved."),
    "完成核对并继续" to listOf("Finish verification and continue"),
    "使用恢复密钥" to listOf("Use recovery key"),
    "输入完整恢复密钥并设置新主密码。成功后恢复密钥保持有效。" to listOf("Enter the complete recovery key and set a new master password. The recovery key remains valid."),
    "新主密码" to listOf("New master password"),
    "再次输入" to listOf("Enter again"),
    "重置并解锁" to listOf("Reset and unlock"),
    "验证主密码" to listOf("Verify master password"),
    "当前主密码" to listOf("Current master password"),
    "验证" to listOf("Verify"),
    "没有可用的登录条目" to listOf("No login items are available"),
    "没有找到匹配的条目" to listOf("No matching items found"),
    "其他动态码" to listOf("Other verification codes"),
    "其他登录条目" to listOf("Other login items"),
    "没有符合条件的条目" to listOf("No matching items"),
    "移入标签" to listOf("Move to tag"),
    "添加标签" to listOf("Add tag"),
    "全部标签" to listOf("All tags"),
    "无标签" to listOf("Untagged"),
    "重命名标签" to listOf("Rename tag"),
    "标签处理" to listOf("Manage tags"),
    "新标签名" to listOf("New tag name"),
    "标签名称" to listOf("Tag name"),
    "删除条目" to listOf("Delete item"),
    "批量删除" to listOf("Delete selected items"),
    "新建空库" to listOf("Create an empty vault"),
    "账户名" to listOf("Vault name"),
    "恢复账户" to listOf("Restore vault"),
    "验证已删除的账户" to listOf("Verify deleted vault"),
    "原主密码" to listOf("Previous master password"),
    "验证并导入" to listOf("Verify and import"),
    "导入到新账户" to listOf("Import into a new vault"),
    "尚无账户，请点右侧添加" to listOf("No vaults yet. Use the add button on the right."),
    "密钥版本不一致" to listOf("Key versions differ"),
    "取消同步" to listOf("Cancel sync"),
    "远端主密码" to listOf("Remote master password"),
    "远端恢复密钥" to listOf("Remote recovery key"),
    "验证远端密码" to listOf("Verify remote password"),
    "验证恢复密钥" to listOf("Verify recovery key"),
    "保留本端密钥" to listOf("Keep local key"),
    "采用远端密钥" to listOf("Use remote key"),
    "库 ID: " to listOf("Vault ID: "),
    "同步与数据迁移" to listOf("Sync and data transfer"),
    "安全设置" to listOf("Security settings"),
    "导出可恢复备份，或从其他密码管理器导入数据" to listOf("Export recoverable backups or import data from another password manager"),
    "关联云端文件/WebDAV，实现多设备数据同步" to listOf("Connect cloud storage or WebDAV to sync across devices"),
    "正在处理云端保险库…" to listOf("Processing cloud vault…"),
    "正在检测远端数据…" to listOf("Checking remote data…"),
    "管理自动填充" to listOf("Manage Autofill"),
    "启用自动填充" to listOf("Enable Autofill"),
    "管理通行密钥" to listOf("Manage passkeys"),
    "启用通行密钥" to listOf("Enable passkeys"),
    "无法打开自动填充设置，请在系统设置中搜索“自动填充”" to listOf("Could not open Autofill settings. Search for “Autofill” in system settings."),
    "无法打开通行密钥设置，请在系统设置中搜索“密码与帐号”" to listOf("Could not open passkey settings. Search for “Passwords and accounts” in system settings."),
    "同步中…" to listOf("Syncing…"),
    "扫描二维码同步" to listOf("Scan QR code to sync"),
    "连接 WebDAV" to listOf("Connect WebDAV"),
    "填写 WebDAV 文件夹地址，程序会在其中使用当前账户对应的加密保险库文件。" to listOf("Enter a WebDAV folder address. FAEVault will use the encrypted vault file for the current vault in that folder."),
    "WebDAV 文件夹地址" to listOf("WebDAV folder address"),
    "密码或应用专用密码" to listOf("Password or app password"),
    "选择 PKCS#12 客户端证书" to listOf("Choose PKCS#12 client certificate"),
    "重新选择客户端证书" to listOf("Choose a different client certificate"),
    "客户端证书密码" to listOf("Client certificate password"),
    "Windows 域" to listOf("Windows domain"),
    "Android 不提供通用的 Windows 域凭据接口，此模式会在验证时明确拒绝。" to listOf("Android does not provide a general Windows domain credential API, so this mode will be rejected during verification."),
    "Android 不提供系统 Kerberos 票据接口，此模式会在验证时明确拒绝。" to listOf("Android does not provide a system Kerberos ticket API, so this mode will be rejected during verification."),
    "自签名证书 SHA-256 指纹" to listOf("Self-signed certificate SHA-256 fingerprint"),
    "自动创建远端目录" to listOf("Create remote folder automatically"),
    "配置按当前保险库隔离，并由 Android Keystore 加密。自签名证书必须填写准确指纹。" to listOf("Settings are isolated per vault and encrypted with Android Keystore. Enter the exact fingerprint for a self-signed certificate."),
    "正在验证" to listOf("Verifying…"),
    "验证并连接" to listOf("Verify and connect"),
    "确认上传覆盖云端" to listOf("Confirm remote vault overwrite"),
    "确认下载覆盖" to listOf("Confirm local replacement"),
    "再次确认本地数据风险" to listOf("Confirm local data risk again"),
    "继续" to listOf("Continue"),
    "确认覆盖本地" to listOf("Replace local vault"),
    "确认启用云端同步" to listOf("Confirm cloud sync"),
    "确认取消关联" to listOf("Confirm disconnect"),
    "重新关联云端硬盘" to listOf("Reconnect cloud drive"),
    "选择云端目录后，程序会自动查找保险库文件。直接选择已有文件时，将继续请求其所在目录权限，以便检测远端文件被删除、替换或出现同名冲突。" to listOf("Choose a cloud folder and FAEVault will find the vault file automatically. If you choose an existing file, folder access will also be requested so deletion, replacement and name conflicts can be detected."),
    "选择云端目录" to listOf("Choose cloud folder"),
    "选择已有文件" to listOf("Choose existing file"),
    "未获得云端目录权限" to listOf("Cloud folder access was not granted"),
    "创建云端保险库文件" to listOf("Create cloud vault file"),
    "云端已有保险库数据" to listOf("Cloud vault data already exists"),
    "WebDAV 已有保险库数据" to listOf("WebDAV vault data already exists"),
    "请选择先拉取并合并双方数据，或上传覆盖远端，亦或下载远端文件覆盖本地。" to listOf("Choose whether to download and merge both sides, overwrite the remote vault, or replace the local vault with the remote file."),
    "同步合并" to listOf("Download and merge"),
    "重新生成恢复密钥" to listOf("Generate a new recovery key"),
    "请先保存并复核新密钥。只有新密钥通过验证且写入成功后，旧密钥才会失效。" to listOf("Save and verify the new key first. The old key becomes invalid only after the new key is verified and saved successfully."),
    "需要相机权限" to listOf("Camera access required"),
    "相机权限已被永久拒绝，请前往系统设置手动授予相机权限。" to listOf("Camera access was permanently denied. Grant it manually in system settings."),
    "删除账户" to listOf("Delete vault"),
    "启用密码检测" to listOf("Enable password checks"),
    "关闭后不再检测、标记或置顶泄露条目。" to listOf("When disabled, exposed items are no longer checked, marked or pinned."),
    "联网检测密码泄露" to listOf("Check passwords against online breach data"),
    "使用密码哈希前5位查询" to listOf("Queries with the first five characters of the password hash"),
    "自动检测周期" to listOf("Automatic check interval"),
    "检测中" to listOf("Checking…"),
    "立即检测" to listOf("Check now"),
    "密码安全" to listOf("Password security"),
    "正在检查保险库中的密码风险" to listOf("Checking passwords in the vault"),
    "查看密码健康状态并管理安全检测" to listOf("Review password health and manage security checks"),
    "正在扫描" to listOf("Scanning…"),
    "保险库" to listOf("FAEVault"),
    "邮箱已复制" to listOf("Email address copied"),
    "条目" to listOf("Items"),
    "两栏" to listOf("Two columns"),
    "进入" to listOf("Open"),
    "收起" to listOf("Collapse"),
    "展开" to listOf("Expand"),
    "双方内容一致" to listOf("Both sides match"),
    "远端有待合并修改" to listOf("Remote changes need merging"),
    "本地有待上传修改" to listOf("Local changes need uploading"),
    "双方均有修改" to listOf("Both sides have changes"),
    "检测到同步冲突" to listOf("Sync conflicts found"),
    "远端文件不存在" to listOf("Remote file does not exist"),
    "远端检测失败" to listOf("Remote check failed"),
    "等待检测" to listOf("Waiting to check"),
    "只读取远端文件，不会修改本地或上传数据" to listOf("This only reads the remote file; it will not change local data or upload anything"),
    "已核对条目、回收站与删除日志，无需合并或覆盖" to listOf("Items, Trash and deletion history match; no merge or overwrite is needed"),
    "重命名账户" to listOf("Rename vault"),
    "新账户名" to listOf("New vault name"),
    "修改主密码只会重新包装数据密钥，现有恢复密钥不受影响。" to listOf("Changing the master password only rewraps the data key. The current recovery key is unaffected."),
    "设置导出口令" to listOf("Set export password"),
    "加密备份使用独立的导出口令；与主密码无关。" to listOf("Encrypted backups use a separate export password, independent of the master password."),
    "导出口令" to listOf("Export password"),
    "输入备份口令" to listOf("Enter backup password"),
    "备份口令" to listOf("Backup password"),
    "冲突处理" to listOf("Conflict handling"),
    "当同名+同用户名条目内容不一致时，统一采用哪种策略？" to listOf("When items with the same name and username differ, which strategy should be used?"),
    "覆盖现有" to listOf("Overwrite existing item"),
    "保留副本" to listOf("Keep both"),
    "跳过冲突" to listOf("Skip conflicts"),
    "跨账户合并提醒" to listOf("Cross-vault merge warning"),
    "仍然合并" to listOf("Merge anyway"),
    "敏感内容二次保护" to listOf("Confirm sensitive-content protection"),
    "密码、卡号等敏感内容点击显示后，到时间会自动重新隐藏。" to listOf("Revealed sensitive values such as passwords and card numbers are hidden again after this time."),
    "不自动清理" to listOf("Never clean automatically"),
    "不自动隐藏" to listOf("Never hide automatically"),
    "外观" to listOf("Appearance"),
    "跟随系统" to listOf("Follow system"),
    "浅色" to listOf("Light"),
    "深色" to listOf("Dark"),
    "布局" to listOf("Layout"),
    "应用语言" to listOf("App language"),
    "简体中文" to listOf("Simplified Chinese"),
    "选择程序使用的语言" to listOf("Choose the app language"),
    "生物识别解锁" to listOf("Biometric unlock"),
    "设备中登记的所有强生物特征均可解锁此保险库。多人共用设备时，建议仅使用主密码。" to listOf("Any strong biometric enrolled on this device can unlock this vault. Use only the master password on a shared device."),
    "设备中登记的所有强生物特征均可解锁此保险库。确认风险后，需要再次验证当前主密码。" to listOf("Any strong biometric enrolled on this device can unlock this vault. After accepting this risk, verify the current master password again."),
    "自动填充" to listOf("Autofill"),
    "密码为空" to listOf("Password is empty"),
    "自动填充：已启用" to listOf("Autofill: enabled"),
    "自动填充：未启用" to listOf("Autofill: disabled"),
    "自动填充：系统不支持" to listOf("Autofill: not supported"),
    "通行密钥服务：已启用" to listOf("Passkey provider: enabled"),
    "通行密钥服务：未启用" to listOf("Passkey provider: disabled"),
    "锁定中" to listOf("Locked"),
    "无账户" to listOf("No vaults"),
    "尝试次数过多，请稍后再试" to listOf("Too many attempts. Try again later."),
    "尝试次数过多，已进入冷却" to listOf("Too many attempts. Unlocking is temporarily disabled."),
    "保险库不存在或已删除" to listOf("The vault does not exist or was deleted"),
    "生物识别绑定已失效，请使用主密码" to listOf("The biometric binding is no longer valid. Use the master password."),
    "生物识别不可用，请使用主密码" to listOf("Biometrics are unavailable. Use the master password."),
    "从保险库填充" to listOf("Fill from FAEVault"),
    "保存到保险库" to listOf("Save to FAEVault"),
    "创建通行密钥" to listOf("Create a passkey"),
    "保存密码" to listOf("Save password"),
    "使用通行密钥" to listOf("Use passkey"),
    "填充密码" to listOf("Fill password"),
    "选择通行密钥" to listOf("Choose a passkey"),
    "尚未创建保险库，请先打开保险库应用完成设置。" to listOf("No vault has been created. Open FAEVault to finish setup."),
    "切换" to listOf("Switch"),
    "生物识别" to listOf("Biometrics"),
    "正在解密…" to listOf("Decrypting…"),
    "选择要解锁的保险库" to listOf("Choose a vault to unlock"),
    "选择登录账号" to listOf("Choose a login"),
    "未找到精确匹配，可手动选择" to listOf("No exact match was found. Choose a login manually."),
    "搜索名称、用户名…" to listOf("Search name or username…"),
    "匹配" to listOf("Match"),
    "新建登录条目" to listOf("Create login item"),
    "未填写用户名" to listOf("No username"),
    "密码已填写" to listOf("Password included"),
    "选择要更新的条目，或新建一条" to listOf("Choose an item to update, or create a new one"),
    "新建条目" to listOf("Create item"),
    "已保存登录条目" to listOf("Login item saved"),
    "凭据未发生变化，无需保存" to listOf("The credential has not changed. Nothing needs to be saved."),
    "保存失败，请重试" to listOf("Could not save. Try again."),
    "凭据状态已变化，请重试" to listOf("The credential changed. Try again."),
    "已更新登录条目" to listOf("Login item updated"),
    "更新失败，请重试" to listOf("Could not update. Try again."),
    "条目已变化，请重试" to listOf("The item changed. Try again."),
    "从文件导入" to listOf("Import from file"),
    "当前编辑尚未保存，确定放弃吗？" to listOf("Your changes have not been saved. Discard them?"),
    "放弃编辑？" to listOf("Discard changes?"),
    "继续编辑" to listOf("Keep editing"),
    "放弃" to listOf("Discard"),
    "导入" to listOf("Import"),
    "导出" to listOf("Export"),
    "返回" to listOf("Back"),
    "恢复密钥" to listOf("Recovery key"),
    "更多操作" to listOf("More actions"),
    "二维码缺少有效的 HTTPS 配对信息" to listOf("The QR code does not contain valid HTTPS pairing information"),
    "配置泄露检测频率，开启联网密码泄露检查" to listOf("Configure password check frequency and online breach checks"),
    "请先关联云端硬盘或 WebDAV" to listOf("Connect cloud drive or WebDAV first"),
    "取消并关闭" to listOf("Cancel and close"),
    "收起认证方式" to listOf("Collapse authentication methods"),
    "选择认证方式" to listOf("Choose authentication method"),
    "所选目录不包含刚才选择的保险库文件" to listOf("The selected folder does not contain the vault file you chose"),
    "所选云端目录未授予持久读写权限，关联未保存" to listOf("Persistent access to the selected cloud folder was not granted, so the connection was not saved"),
    "所选云端文件未授予持久读写权限，关联未保存" to listOf("Persistent access to the selected cloud file was not granted, so the connection was not saved"),
    "无法读取关联的云端目录，请检查云盘状态或重新关联" to listOf("Could not read the connected cloud folder. Check cloud storage or reconnect."),
    "无法读取客户端证书" to listOf("Could not read the client certificate"),
    "云盘未授予目录持久读写权限，可选择仅关联文件" to listOf("Persistent folder access was not granted. You can connect only the file instead."),
    "支持主流密码管理器、CSV、JSON 导入后合并" to listOf("Import and merge data from popular password managers, CSV and JSON files"),
    "需要相机权限才能扫码" to listOf("Camera access is required to scan"),
    "WebDAV 文件夹地址无效" to listOf("The WebDAV folder address is invalid"),
    "新建账户" to listOf("Create vault"),
    "新增" to listOf("New"),
    "Google, GitHub 等" to listOf("Google, GitHub, etc."),
    "YYYY-MM-DD 或 长期" to listOf("YYYY-MM-DD or No expiry"),
    "预计破解时长：少于 1 秒" to listOf("Estimated crack time: less than 1 second"),
    "预计破解时长：超过 1 万亿年" to listOf("Estimated crack time: over 1 trillion years"),
    "生成的密码" to listOf("Generated password"),
    "扫码同步要求两台设备连接同一局域网。跨网络或仅一端使用移动数据时无法连接。" to listOf("QR sync requires both devices to be on the same local network. It cannot connect across separate networks or when only one device uses mobile data."),
    "破解预估" to listOf("Crack estimate"),
    "少于 1 秒" to listOf("less than 1 second"),
    "超过 1 万亿年" to listOf("over 1 trillion years"),
    "再按一次返回桌面" to listOf("Press Back again to exit"),
    "关闭通知" to listOf("Dismiss notification"),
    "全部风险" to listOf("All findings"),
    "检测结果" to listOf("Check results"),
    "包含高风险问题的条目，请优先处理。" to listOf("Items with high-risk issues; address them first."),
    "无高风险问题，但仍有可改进之处。" to listOf("No high-risk issues, but there is room for improvement."),
    "未发现本地问题；不代表密码从未泄露。" to listOf("No issues found locally; this does not rule out previous exposure."),
    "双方内容一致，未发现需要合并的修改。" to listOf("Both sides match. No changes need to be merged."),
    "已完成拉取、合并、上传和远端读回校验。" to listOf("Download, merge, upload and remote read-back verification completed."),
    "已完成拉取和合并；远端已包含合并结果，无需重复上传。" to listOf("Download and merge completed. The remote vault already contains the merged result, so no upload was needed."),
    "新增" to listOf("Added"),
    "取远端" to listOf("Used remote"),
    "留本地" to listOf("Kept local"),
    "保留双份" to listOf("Kept both"),
    "无变化" to listOf("Unchanged"),
    "已清理" to listOf("Purged"),
    "忽略过期删除日志" to listOf("Ignored expired deletion history"),
    "合并重复条目" to listOf("Merged duplicates"),
    "使用保险库" to listOf("Use FAEVault"),
    "尚未创建保险库" to listOf("No vault has been created"),
    "选择保险库" to listOf("Choose a vault"),
    "保险库不存在" to listOf("Vault not found"),
    "请求无效、已过期或未获授权" to listOf("The request is invalid, expired or unauthorized"),
    "通行密钥已存在" to listOf("This passkey already exists"),
    "保险库数据异常" to listOf("The vault data is invalid"),
    "已检测到文档，按下方按钮拍摄" to listOf("Document detected. Use the button below to capture it."),
    "把文档放进画面，会自动框选" to listOf("Place the document in the frame for automatic edge detection"),
    "拍摄" to listOf("Capture"),
    "拖动四角调整裁剪范围" to listOf("Drag the corners to adjust the crop"),
    "闪光灯" to listOf("Flash"),
    "重拍" to listOf("Retake"),
    "无法返回裁剪结果" to listOf("Could not return the cropped image"),
    "裁剪保存失败" to listOf("Could not save the crop"),
    "关闭闪光灯" to listOf("Turn off flash"),
    "打开闪光灯" to listOf("Turn on flash"),
    "框内有多个有效二维码，请只保留一个" to listOf("Multiple valid QR codes are in the frame. Keep only one."),
    "将目标二维码单独置于框内" to listOf("Place only the target QR code in the frame"),
    "已识别，正在跳转…" to listOf("QR recognized, opening…"),
    "这不是局域网导入二维码。请在对方设备使用「局域网导入 → 发送」生成专用二维码后再扫描" to listOf("This is not a LAN import QR. Generate a dedicated import QR on the other device via 'LAN import → Send' and scan it."),
    "已识别但不是有效的同步二维码" to listOf("Recognized but not a valid sync QR code"),
    "恢复密钥无效" to listOf("The recovery key is invalid"),
    "重命名失败" to listOf("Could not rename the vault"),
    "密码错误，无法验证账户所有权" to listOf("Incorrect password. Vault ownership could not be verified."),
    "解锁失败" to listOf("Could not unlock the vault"),
    "泄露检测已关闭" to listOf("Breach checks are disabled"),
    "没有需要检测的条目" to listOf("No items need checking"),
    "局域网同步已完成" to listOf("Local network sync completed"),
    "云端同步已完成" to listOf("Cloud sync completed"),
    "文件已写入并通过读回校验；远端同步状态由云盘应用管理" to listOf("The file was written and verified by reading it back. Remote synchronization is managed by the cloud storage app."),
    "请先连接 WebDAV" to listOf("Connect WebDAV first"),
    "请选择至少两条条目进行合并" to listOf("Select at least two items to merge"),
    "远端密码验证失败" to listOf("Remote master password verification failed"),
    "远端恢复密钥验证失败" to listOf("Remote recovery key verification failed"),
    "已采用远端密钥，请重新登录" to listOf("The remote key is now active. Sign in again."),
    "已保留本端密钥并完成同步" to listOf("The local key was kept and synchronization completed"),
    "同步失败" to listOf("Synchronization failed"),
    "安全保存此条目" to listOf("Save this item securely"),
    "按当前规则实时生成" to listOf("Generated live using the current settings"),
    "保存恢复密钥" to listOf("Save recovery key"),
    "保存或分享恢复单" to listOf("Save or share recovery sheet"),
    "保存图片" to listOf("Save image"),
    "本地加密 · 与桌面端 .pmv 互通" to listOf("Encrypted locally · Compatible with desktop .pmv files"),
    "本端指纹" to listOf("Local fingerprint"),
        "操作敏感内容前验证主密码" to listOf("Verify the master password before operating on sensitive content"),
    "所有图像显示均进行模糊处理，保护图像隐私。" to listOf("All image displays are blurred to protect image privacy."),
    "轻触画面对焦 · 双指缩放" to listOf("Tap to focus · Pinch to zoom"),
    "轻触画面对焦 · 双指缩放 · 点倍率切远近" to listOf("Tap to focus · Pinch to zoom · Tap the ratio to switch"),
    "拍照获取图像" to listOf("Capture image"),
    "关闭图像模糊需要验证当前主密码。" to listOf("Verify your current master password to turn off image blur."),
    "请输入有效日期（YYYY-MM-DD）。" to listOf("Enter a valid date (YYYY-MM-DD)."),
    "图像模糊" to listOf("Blur images"),
    "所有图像自动模糊处理" to listOf("All images are automatically blurred"),
    "城市" to listOf("City"),
    "处理失败" to listOf("Processing failed"),
    "大写" to listOf("Uppercase"),
    "当前已登录账户" to listOf("Currently unlocked vault"),
    "导出加密备份需要验证当前主密码。" to listOf("Verify the current master password before exporting an encrypted backup."),
    "导出原始保险库文件需要验证当前主密码。" to listOf("Verify the current master password before exporting the original vault file."),
    "导出压缩包需要验证当前主密码。" to listOf("Verify the current master password before exporting an archive."),
    "导出压缩包" to listOf("Export archive"),
    "导入后用桌面端原主密码解锁。" to listOf("After importing, unlock with the original desktop master password."),
    "登录凭证" to listOf("Login credentials"),
    "点击验证主密码查看" to listOf("Verify the master password to view"),
    "读取应用列表" to listOf("Read app list"),
    "分行/支行" to listOf("Branch"),
    "分行联行号" to listOf("Branch routing code"),
    "服务" to listOf("Service"),
    "附件大小校验失败" to listOf("Attachment size verification failed"),
    "附件模块总容量不能超过 32 MB" to listOf("An attachment module cannot exceed 32 MB in total"),
    "附件模块总容量仅受可用空间限制" to listOf("Attachment module capacity is limited only by available space"),
    "附件完整性校验失败" to listOf("Attachment integrity verification failed"),
    "复制图片" to listOf("Copy image"),
    "该类别下暂无条目" to listOf("No items in this category"),
    "该密码在常见泄露 / 弱密码字典中，强烈建议更换" to listOf("This password appears in common breach or weak-password lists. Change it as soon as possible."),
    "港澳通行证" to listOf("Mainland Travel Permit for Hong Kong and Macao"),
    "操作登录、WI-FI以外的条目时需要验证主密码" to listOf("Verify the master password when operating on items other than logins and Wi-Fi."),
    "关闭「敏感内容二次保护」会降低保护等级，需要验证当前主密码。" to listOf("Disabling sensitive-content protection reduces protection and requires the current master password."),
    "关闭生物识别解锁需要验证当前主密码。" to listOf("Verify the current master password before disabling biometric unlock."),
    "关闭自动锁定后，手动锁定前设备将保持解锁状态。如需保护，建议保持开启。" to listOf("If automatic locking is disabled, the vault stays unlocked until you lock it manually. Keep it enabled for protection."),
    "关联程序包名" to listOf("Linked app package"),
    "关联的云端文件已被删除，请重新关联" to listOf("The connected cloud file was deleted. Reconnect it."),
    "管理地址" to listOf("Admin address"),
    "国家 / 地区" to listOf("Country / region"),
    "很强" to listOf("Very strong"),
    "获取应用列表" to listOf("Get app list"),
    "即将自动删除" to listOf("Will be deleted soon"),
    "继续覆盖" to listOf("Continue overwrite"),
    "加长" to listOf("Increase"),
    "检测到两端密钥不一致" to listOf("Keys differ between devices"),
    "建议：仅在确认这两份库本就属于同一账户时继续；否则请取消，改用「在登录页新建账户后再导入」。" to listOf("Continue only if both vaults belong to the same account. Otherwise cancel, create a new vault on the sign-in screen, and import there."),
    "建议只在迁移到其他工具时临时导出。完成导入后请立即删除该文件，不要保存到云盘、聊天软件、邮件或下载目录长期保留。" to listOf("Export only temporarily when moving to another tool. Delete the file immediately after importing it; do not keep it in cloud storage, chat, email or Downloads."),
    "建议至少 16 位" to listOf("At least 16 characters recommended"),
    "仅关联文件" to listOf("Connect file only"),
    "开发者：FAE" to listOf("Developer: FAE"),
    "开户行" to listOf("Issuing bank"),
    "开启：进入这些条目的敏感字段前需输入当前主密码。" to listOf("On: enter the current master password before accessing sensitive fields in these items."),
    "可能系统拒绝了 \"读取应用列表\" 权限。\n请到应用权限设置中开启。" to listOf("The system may have denied app-list access.\nEnable it in the app permission settings."),
    "可以仅关联刚才选择的文件并继续同步，但程序将无法可靠检测该文件在云端被删除、替换或出现同名冲突。建议返回并选择该文件所在目录。" to listOf("You can connect only the selected file, but deletion, replacement and same-name conflicts may not be detected reliably. Go back and choose its folder when possible."),
    "客户端证书 mTLS" to listOf("Client certificate mTLS"),
    "客户端证书超过 1 MB 安全限制" to listOf("The client certificate exceeds the 1 MB safety limit"),
    "两端凭据已验证。请选择要保留哪一端的密钥槽：" to listOf("Credentials for both sides are verified. Choose which key slots to keep:"),
    "每个附件模块最多保存 20 个文件" to listOf("Each attachment module can contain up to 20 files"),
    "密码存在差异，将采用最新修改版本。" to listOf("Passwords differ. The most recently updated version will be used."),
    "敏感内容复制后，到时间会自动清理剪贴板，避免久留泄露。" to listOf("Sensitive values are cleaned from the clipboard after this time to avoid exposure."),
    "默认" to listOf("Default"),
    "Passkey 默认存储模式" to listOf("Default Passkey storage mode"),
    "每次创建均确认" to listOf("Confirm on every creation"),
    "每次创建 Passkey 时选择同步型或本设备高安全性。" to listOf("Choose syncable or high-security storage on this device every time a Passkey is created."),
    "创建时仍可单独切换。同步型默认进入 PMV；高安全性模式的私钥只存在于当前设备。" to listOf("You can still choose per credential. Syncable Passkeys go into PMV by default; high-security private keys remain only on this device."),
    "PMV 同步型（推荐）" to listOf("PMV syncable (recommended)"),
    "PMV 同步型" to listOf("PMV syncable"),
    "待安全升级（旧版软件私钥）" to listOf("Security upgrade required (legacy software private key)"),
    "存储模式" to listOf("Storage mode"),
    "备份状态" to listOf("Backup status"),
    "已确认同步或备份" to listOf("Confirmed synced or backed up"),
    "尚未确认同步或备份" to listOf("Not yet confirmed synced or backed up"),
    "可用范围" to listOf("Availability"),
    "设备密钥已丢失" to listOf("Device key is missing"),
    "暂无同步型 Passkey" to listOf("No syncable Passkeys yet"),
    "本设备高安全性" to listOf("High security on this device"),
    "Android Keystore 私钥不可导出；设备损坏或重置后无法恢复。" to listOf("The Android Keystore private key cannot be exported and cannot be recovered after device loss or reset."),
    "已复制" to listOf("Copied"),
    "偏弱" to listOf("Weak"),
    "其他" to listOf("Other"),
    "启用联网同步需要验证当前主密码。" to listOf("Verify the current master password before enabling online sync."),
    "强" to listOf("Strong"),
    "切换浅色 / 深色 / 跟随系统" to listOf("Switch between light, dark and system theme"),
    "请输入远端主密码以验证身份" to listOf("Enter the remote master password to verify identity"),
    "请选择保留哪端密钥" to listOf("Choose which key to keep"),
    "取消 WebDAV 关联需要验证当前主密码。" to listOf("Verify the current master password before disconnecting WebDAV."),
    "取消云端硬盘关联需要验证当前主密码。" to listOf("Verify the current master password before disconnecting cloud drive."),
    "确定要删除吗？" to listOf("Delete this?"),
    "确认创建" to listOf("Create"),
    "删除附件" to listOf("Delete attachment"),
    "删除确认" to listOf("Confirm deletion"),
    "删除图片" to listOf("Delete image"),
    "尚无条目，点击右下角新增" to listOf("No items yet. Use the button in the lower-right corner to add one."),
    "少于 1 秒" to listOf("Less than 1 second"),
    "身份证" to listOf("National ID card"),
    "省 / 州" to listOf("State / province"),
    "数据库类型" to listOf("Database type"),
    "数据库引擎" to listOf("Database engine"),
    "缩短" to listOf("Decrease"),
    "所需权限已被永久拒绝，请前往系统设置手动授权。" to listOf("The required permission was permanently denied. Grant it manually in system settings."),
    "特殊符号" to listOf("Special characters"),
    "同名文件冲突" to listOf("Same-name file conflict"),
    "图片解码失败" to listOf("Could not decode the image"),
    "未获取到应用列表" to listOf("Could not retrieve the app list"),
        "未设置凭证" to listOf("No credential configured"),
    "未识别到二维码" to listOf("No QR code recognized"),
    "文件已删除" to listOf("File deleted"),
    "文件已替换" to listOf("File replaced"),
    "无操作超时后自动锁定" to listOf("Lock automatically after inactivity"),
    "自动锁定已关闭，手动锁定前设备将保持解锁状态" to listOf("Auto-lock is off. The vault stays unlocked until you lock it manually."),
    "无法创建文件" to listOf("Could not create the file"),
    "无法读取相机返回的图片" to listOf("Could not read the image returned by the camera"),
    "无法解析当前位置" to listOf("Could not resolve the current location"),
    "无关联包名" to listOf("No linked package"),
    "无匹配结果" to listOf("No matches"),
    "无匹配条目" to listOf("No matching items"),
    "无认证" to listOf("No authentication"),
    "系统定位未开启" to listOf("System location is turned off"),
    "相册权限已被永久拒绝。请前往系统设置手动授予相册权限。" to listOf("Photo access was permanently denied. Grant it manually in system settings."),
    "相机权限已被永久拒绝。请前往系统设置手动授予相机权限。" to listOf("Camera access was permanently denied. Grant it manually in system settings."),
    "详细地址" to listOf("Street address"),
    "小写" to listOf("Lowercase"),
    "修改主密码需要再次验证当前主密码。" to listOf("Verify the current master password again before changing it."),
    "选择程序" to listOf("Choose app"),
    "选择主页布局模式" to listOf("Choose home layout"),
    "选中的条目包含不同的标题、用户名或密码，请指定合并后使用哪个。" to listOf("The selected items have different titles, usernames or passwords. Choose the values to use after merging."),
    "一般" to listOf("Fair"),
    "依赖方域名" to listOf("Relying-party domain"),
    "已解锁敏感内容" to listOf("Sensitive content unlocked"),
    "已知晓并启用" to listOf("I understand; enable"),
    "异常" to listOf("Error"),
    "用户名/AppId" to listOf("Username / App ID"),
    "用手机相机扫码即可连接" to listOf("Scan with a phone camera to connect"),
    "邮编" to listOf("Postal code"),
    "邮政编码" to listOf("Postal code"),
    "远端密码验证通过。请输入远端恢复密钥以完成验证。" to listOf("Remote master password verified. Enter the remote recovery key to finish verification."),
    "远端密码已验证" to listOf("Remote master password verified"),
    "远端已变更" to listOf("Remote changed"),
    "远端指纹" to listOf("Remote fingerprint"),
    "云端目录中出现多个同名文件，请重新关联" to listOf("Multiple cloud files have the same name. Reconnect the correct file."),
    "云端文件已被同名文件替换，请重新关联并确认内容" to listOf("The cloud file was replaced by another file with the same name. Reconnect and verify its contents."),
    "云端文件状态异常" to listOf("Cloud file state is invalid"),
    "暂时无法取得位置，请稍后重试" to listOf("Location is temporarily unavailable. Try again later."),
    "暂无账户" to listOf("No vaults"),
    "长按分类并上下拖动可调整顺序" to listOf("Press and drag categories to reorder them"),
    "这是忘记主密码时的最终恢复方式。请离线保存；任何拿到它的人都可以重置主密码。" to listOf("This is the final recovery method if you forget the master password. Keep it offline; anyone who has it can reset the master password."),
    "正常" to listOf("Normal"),
    "证件照片" to listOf("Document images"),
    "指纹" to listOf("Fingerprint"),
    "至少保留一种字符；启用的每一类都会出现至少一次。" to listOf("Keep at least one character type enabled. Every enabled type will appear at least once."),
    "重命名账户需要验证当前主密码。" to listOf("Verify the current master password before renaming the vault."),
    "重新关联 WebDAV 需要验证当前主密码。" to listOf("Verify the current master password before reconnecting WebDAV."),
    "重新关联云端硬盘需要验证当前主密码。" to listOf("Verify the current master password before reconnecting cloud drive."),
    "重新生成" to listOf("Generate again"),
    "重新生成恢复密钥需要验证当前主密码。成功后旧密钥立即失效。" to listOf("Verify the current master password before generating a new recovery key. The old key becomes invalid immediately after success."),
    "主密码不正确" to listOf("Incorrect master password"),
    "自定义标题" to listOf("Custom title"),
    "自动检测已关闭" to listOf("Automatic checks are disabled"),
    "OAuth 2.0 访问令牌" to listOf("OAuth 2.0 access token"),
    "• 保留本端版本：两端统一使用本端密钥版本\n• 采用远端版本：两端统一使用远端密钥版本\n\n选择后立即执行同步并推送至对方设备。" to listOf("• Keep local version: use the local key version on both devices\n• Use remote version: use the remote key version on both devices\n\nAfter you choose, synchronization starts immediately and the result is sent to the other device."),
    "6 位" to listOf("6 digits"),
    "7 位" to listOf("7 digits"),
    "8 位" to listOf("8 digits"),
    "本地独有条目、较新修改和本地删除记录都可能被远端版本覆盖。程序会保留 .download.bak 备份，但仍建议先导出备份。确定继续吗？" to listOf("Local-only items, newer changes and local deletion records may be replaced by the remote version. A .download.bak backup will be kept, but exporting a backup first is still recommended. Continue?"),
    "超过 1 万亿年" to listOf("Over 1 trillion years"),
    "长按拖动" to listOf("Press and drag"),
    "云端仅接收加密后的保险库文件，但数据安全仍依赖主密码强度、云端账户和设备安全。默认同步会先拉取并合并；「上传覆盖云端」会直接替换远端文件，可能丢失远端独有修改。请确认已了解这些密码数据安全与覆盖风险。" to listOf("Cloud storage receives only the encrypted vault file, but security still depends on the master password, cloud account and device. Standard sync downloads and merges first; “Overwrite remote vault” replaces the remote file directly and may discard remote-only changes. Confirm that you understand these risks."),
    "id 不重合时直接加入，可能让两个账户的内容混在一起。" to listOf("Items with different IDs are added directly, which may mix the contents of two vaults."),
    "安全笔记" to listOf("Secure note"),
    "服务器" to listOf("Server"),
    "解锁时检查回收站，自动删除超过设定天数的条目" to listOf("Check Trash when unlocking and automatically delete items older than the selected period"),
    "启用生物识别失败" to listOf("Could not enable biometric unlock"),
    "生物识别解锁失败" to listOf("Biometric unlock failed"),
    "生物识别已变更，原绑定已失效，请用主密码解锁后到「设置 → 启用生物识别解锁」重新绑定" to listOf("Your biometric enrollment changed. Unlock with the master password, then enable biometric unlock again in Settings."),
    "已启用生物识别解锁" to listOf("Biometric unlock enabled"),
    "自定义" to listOf("Custom"),
    "密钥已复制。第 1 组 PMRK1 是格式标识，不参与校验；以下序号按完整密钥从左到右计算，每组从 5 个候选中选择。" to listOf("Key copied. Group 1, PMRK1, is a format marker and is not verified. The following positions are counted from left to right across the complete key; choose one of five candidates for each group."),
    "恢复单已保存或分享。第 1 组 PMRK1 是格式标识，不参与校验；以下序号按完整密钥从左到右计算，每组从 5 个候选中选择。" to listOf("Recovery sheet saved or shared. Group 1, PMRK1, is a format marker and is not verified. The following positions are counted from left to right across the complete key; choose one of five candidates for each group."),
    "暂不支持预览此图表类型，已显示源码" to listOf("This diagram type cannot be previewed yet; showing the source"),
)

private val UI_DYNAMIC = listOf(
    Regex("^共 (\\d+) 条$") to listOf("$1 items"),
    Regex("^高风险 (\\d+)$") to listOf("High risk $1"),
    Regex("^需改进 (\\d+)$") to listOf("Needs attention $1"),
    Regex("^未发现问题 (\\d+)$") to listOf("No issues found $1"),
    Regex("^(\\d+) 个未发现问题$") to listOf("$1 with no issues found"),
    Regex("^共(?:检查|检测) (\\d+) 个含密码条目$") to listOf("$1 password items checked"),
    Regex("^联系：(.+)$") to listOf("Contact: $1"),
    Regex("^当前指纹：(.+)$") to listOf("Current fingerprint: $1"),
    Regex("^设置时间：(.+)$") to listOf("Created: $1"),
    Regex("^保存日期：(.+)$") to listOf("Saved on: $1"),
    Regex("^已泄露 (.+) 次$") to listOf("Found in $1 breaches"),
    Regex("^已导入 Wi-Fi「(.+)」$") to listOf("Imported Wi-Fi “$1”"),
    Regex("^已自动识别并填入 (\\d+) 个字段$") to listOf("$1 fields recognized and filled"),
    Regex("^已识别并填入 (\\d+) 个字段$") to listOf("$1 fields recognized and filled"),
    Regex("^拍照处理失败：(.+)$") to listOf("Photo processing failed: $1"),
    Regex("^处理失败：(.+)$") to listOf("Processing failed: $1"),
    Regex("^扫描识别失败：(.+)$") to listOf("Scan recognition failed: $1"),
    Regex("^图片处理失败：(.+)$") to listOf("Image processing failed: $1"),
    Regex("^附件处理失败：(.+)$") to listOf("Attachment processing failed: $1"),
    Regex("^导出失败：(.+)$") to listOf("Export failed: $1"),
    Regex("^导入失败：(.+)$") to listOf("Import failed: $1"),
    Regex("^保存失败：(.+)$") to listOf("Save failed: $1"),
    Regex("^连接失败：(.+)$") to listOf("Connection failed: $1"),
    Regex("^恢复失败：(.+)$") to listOf("Restore failed: $1"),
    Regex("^密钥统一失败：(.+)$") to listOf("Key reconciliation failed: $1"),
    Regex("^扫描：可合并 (\\d+) 组，密码冲突 (\\d+) 组$") to listOf("$1 mergeable groups, $2 password conflicts"),
    Regex("^检测到 (\\d+) 组条目可能指向同一服务$") to listOf("$1 groups may refer to the same service"),
    Regex("^超过 (.+) 后的条目将自动彻底删除$") to listOf("Items older than $1 are deleted automatically"),
    Regex("^超过 (.+) 的条目将被自动彻底删除$") to listOf("Items older than $1 are deleted automatically"),
    Regex("^(\\d+) 个月$") to listOf("$1 months"),
    Regex("^(\\d+) 周$") to listOf("$1 weeks"),
    Regex("^(\\d+) 天$") to listOf("$1 days"),
    Regex("^(\\d+) 秒$") to listOf("$1 seconds"),
    Regex("^(\\d+) 分钟$") to listOf("$1 minutes"),
    Regex("^(\\d+) 分 (\\d+) 秒$") to listOf("$1 min $2 sec"),
    Regex("^每 (\\d+) 个月$") to listOf("Every $1 months"),
    Regex("^每 (\\d+) 周$") to listOf("Every $1 weeks"),
    Regex("^每 (\\d+) 天$") to listOf("Every $1 days"),
    Regex("^空闲 (.+) 后锁定$") to listOf("Lock after $1 of inactivity"),
    Regex("^每 (.+)$") to listOf("Every $1"),
    Regex("^超过 (.+) 后重新检测$") to listOf("Check again after $1"),
    Regex("^(.+) 秒后清理$") to listOf("Clean after $1 seconds"),
    Regex("^(.+) 分钟后清理$") to listOf("Clean after $1 minutes"),
    Regex("^(.+) 秒后隐藏$") to listOf("Hide after $1 seconds"),
    Regex("^(.+) 分钟后隐藏$") to listOf("Hide after $1 minutes"),
    Regex("^共 (\\d+) 条$") to listOf("$1 items"),
    Regex("^将彻底删除全部 (\\d+) 条，此操作不可恢复。$") to listOf("Permanently delete all $1 items? This cannot be undone."),
    Regex("^最后确认：这 (\\d+) 条将无法找回。$") to listOf("Final confirmation: these $1 items cannot be recovered."),
    Regex("^将彻底删除所选 (\\d+) 条，此操作不可恢复。$") to listOf("Permanently delete the selected $1 items? This cannot be undone."),
    Regex("^将彻底删除「(.+)」，此操作不可恢复。$") to listOf("Permanently delete “$1”? This cannot be undone."),
    Regex("^确定将所选 (\\d+) 条移入回收站吗？$") to listOf("Move the selected $1 items to Trash?"),
    Regex("^确定将“(.+)”移入回收站吗？$") to listOf("Move “$1” to Trash?"),
    Regex("^没有符合“(.+)”的条目$") to listOf("No items match “$1”"),
    Regex("^合并选中的 (\\d+) 条$") to listOf("Merge $1 selected items"),
    Regex("^(.+) 条记录 · 将保留最新修改版本$") to listOf("$1 items · The latest version will be kept"),
    Regex("^保留本端版本 v(\\d+)$") to listOf("Keep local version v$1"),
    Regex("^采用远端版本 v(\\d+)$") to listOf("Use remote version v$1"),
    Regex("^认证方式：(.+)$") to listOf("Authentication: $1"),
    Regex("^本地 (\\d+) 项，回收站 (\\d+) · 远端 (\\d+) 项，回收站 (\\d+)$") to listOf("Local: $1 items, $2 in Trash · Remote: $3 items, $4 in Trash"),
    Regex("^远端新增 (\\d+)$") to listOf("$1 new remote"),
    Regex("^采用远端 (\\d+)$") to listOf("$1 taken from remote"),
    Regex("^本地待上传 (\\d+)$") to listOf("$1 local pending upload"),
    Regex("^保留本地 (\\d+)$") to listOf("$1 kept locally"),
    Regex("^删除传播 (\\d+)$") to listOf("$1 deletions propagated"),
    Regex("^远端删除日志 (\\d+)$") to listOf("$1 remote deletion records"),
    Regex("^本地删除日志待上传 (\\d+)$") to listOf("$1 local deletion records pending upload"),
    Regex("^冲突 (\\d+)$") to listOf("$1 conflicts"),
    Regex("^最近检测：(.+)$") to listOf("Last checked: $1"),
    Regex("^保险库  v(.+)$") to listOf("FAEVault  v$1"),
    Regex("^锁定中 (\\d+)s$") to listOf("Locked $1s"),
    Regex("^账户(\\d+)$") to listOf("Vault $1"),
    // 恢复密钥确认弹窗：账户名前缀动态化。紧急规则必须先于通用规则，
    // 否则「X紧急恢复密钥」会被通用规则误切成“X紧急 Recovery Key”。
    Regex("^(.+)紧急恢复密钥$") to listOf("$1 Emergency Recovery Key"),
    Regex("^(.+)恢复密钥$") to listOf("$1 Recovery Key"),
    Regex("^主密码错误，还可尝试 (\\d+) 次$") to listOf("Incorrect master password. $1 attempts remaining."),
    Regex("^PIN 码错误，还可尝试 (\\d+) 次$") to listOf("Incorrect PIN. $1 attempts remaining."),
    Regex("^等待 (\\d+)s$") to listOf("Wait $1s"),
    Regex("^复制 (.+)$") to listOf("Copy $1"),
    Regex("^确定删除已选择的 (\\d+) 条条目？删除后可在回收站中恢复。$") to listOf("Delete the selected $1 items? They can be restored from Trash."),
    Regex("^确定删除「(.+)」？删除后可在回收站中恢复。$") to listOf("Delete “$1”? It can be restored from Trash."),
    Regex("^目录中发现 (\\d+) 个保险库文件，无法唯一确认目标，请改用「选择已有文件」$") to listOf("$1 vault files were found in the folder. Choose “Existing file” to select the correct one."),
    Regex("^生物密钥不可用：(.+)$") to listOf("Biometric key unavailable: $1"),
    Regex("^(.+) 同步结果$") to listOf("$1 sync result"),
    Regex("^同步前本地 (\\d+) 项 · 同步后 (\\d+) 项 · 远端 (\\d+) KB$") to
        listOf("Local before sync: $1 · After sync: $2 · Remote: $3 KB"),
    Regex("^同步前本地 (\\d+) 项 · 同步后 (\\d+) 项$") to listOf("Local before sync: $1 · After sync: $2"),
    Regex("^上传远端：成功 · 读回校验：通过$") to listOf("Remote upload: successful · Read-back verification: passed"),
    Regex("^上传远端：未执行，内容一致 · 远端内容校验：未执行$") to
        listOf("Remote upload: not needed because content matches; verification not performed"),
    Regex("^相机启动失败：(.+)$") to listOf("Could not start the camera: $1"),
    Regex("^拍照失败：(.+)$") to listOf("Could not capture photo: $1"),
    Regex("^「(.+)」将进入回收站，30 天后自动彻底清除。期间可在账户列表页恢复，原生物识别绑定保持有效。$") to
        listOf("“$1” will move to Trash and be deleted automatically after 30 days. It can be restored from the account list, and its biometric binding remains valid."),
    Regex("^「(.+)」处于已删除状态。请输入原主密码以验证所有权，验证通过后将恢复该账户并导入所选文件。$") to
        listOf("“$1” is in Trash. Enter its previous master password to verify ownership, restore it and import the selected file."),
    Regex("^「(.+)」处于已删除状态，30 天内可恢复。点\"恢复账户\"还原原数据；或换个名字以新建。$") to
        listOf("“$1” is in Trash and can be restored within 30 days. Choose “Restore vault” to recover it, or use another name to create a new vault."),
    Regex("^(\\d+)秒$") to listOf("$1 seconds"),
    Regex("^(\\d+) 条$") to listOf("$1 items"),
    Regex("^(.+) 动态码$") to listOf("$1 one-time code"),
    Regex("^(\\d+) 小时后自动删除$") to listOf("Deleted automatically in $1 hours"),
    Regex("^(\\d+) 天后自动删除$") to listOf("Deleted automatically in $1 days"),
    Regex("^(.+) 超过 16 MB$") to listOf("$1 exceeds 16 MB"),
    Regex("^(.+) 是空文件$") to listOf("$1 is empty"),
    Regex("^(.+)：当前版本暂不支持，数据已保留$") to listOf("$1 is not supported by this version. Its data was preserved."),
    Regex("^操作 (.+) 的敏感内容需要验证主密码。$") to listOf("Verify the current master password to operate on $1 sensitive content."),
    Regex("^到期 (.+)$") to listOf("Expires $1"),
    Regex("^第 (\\d+) 组：(.+)$") to listOf("Group $1: $2"),
    Regex("^该密码在公开泄露中出现了 (.+) 次，强烈建议更换$") to listOf("This password appeared in $1 known breaches. Change it as soon as possible."),
    Regex("^检测完成 (\\d+)/(\\d+)$") to listOf("Check complete $1/$2"),
    Regex("^将从(.+)下载完整保险库并替换当前本地文件。此操作不会先执行合并。$") to listOf("The complete vault will be downloaded from $1 and will replace the local file without merging first."),
    Regex("^将清除当前设备与(.+)的关联和本地连接信息，不会删除远端保险库文件。确认继续吗？$") to listOf("Disconnect this device from $1 and clear local connection information? The remote vault file will not be deleted."),
    Regex("^将使用当前本地保险库完整覆盖(.+)文件，云端独有或更新较新的内容将丢失。此操作不会先执行合并。$") to listOf("The local vault will completely overwrite the $1 file without merging. Remote-only or newer content will be lost."),
    Regex("^将已选 (\\d+) 条的所有标签替换为指定标签。$") to listOf("Replace all tags on the $1 selected items with the specified tag."),
    Regex("^两端保险库的密钥版本号不一致：本端 v(\\d+)，远端 v(\\d+)，但密码一致。请选择同步策略：$") to listOf("The key versions differ: local v$1, remote v$2, but the passwords match. Choose a synchronization strategy:"),
    Regex("^请选择第 (\\d+) 组$") to listOf("Choose group $1"),
    Regex("^如继续合并，对方的 (\\d+) 条会按时间戳与当前账户的条目逐一比对。$") to listOf("If you continue, $1 incoming items will be compared with the current vault by timestamp."),
    Regex("^删除「(.+)」是软删除，但仍需再次验证当前主密码。$") to listOf("Deleting “$1” moves it to Trash, but the current master password must still be verified again."),
    Regex("^所选目录中没有发现 \\.pmv 文件。是否创建 (.+)？$") to listOf("No .pmv file was found in the selected folder. Create $1?"),
    Regex("^为已选 (\\d+) 条附加一个标签。$") to listOf("Add a tag to the $1 selected items."),
    Regex("^无法读取 (.+)$") to listOf("Could not read $1"),
    Regex("^无法加载 (.+)$") to listOf("Could not load $1"),
    Regex("^已选 (\\d+)$") to listOf("$1 selected"),
    Regex("^同步周期  ·  (.+)$") to listOf("Sync interval · $1"),
    Regex("^下次预计：(.+)$") to listOf("Next run: $1"),
    Regex("^预计破解时长：约 (\\d+) 秒$") to listOf("Estimated crack time: about $1 seconds"),
    Regex("^预计破解时长：约 (\\d+) 分钟$") to listOf("Estimated crack time: about $1 minutes"),
    Regex("^预计破解时长：约 (\\d+) 小时$") to listOf("Estimated crack time: about $1 hours"),
    Regex("^预计破解时长：约 (\\d+) 天$") to listOf("Estimated crack time: about $1 days"),
    Regex("^预计破解时长：约 ([\\d.]+) 年$") to listOf("Estimated crack time: about $1 years"),
    Regex("^预计破解时长：约 ([\\d.]+) 万年$") to listOf("Estimated crack time: about $1 ten-thousand years"),
    Regex("^预计破解时长：约 ([\\d.]+) 亿年$") to listOf("Estimated crack time: about $1 hundred-million years"),
    Regex("^预计破解时长：约 ([\\d.]+) 万亿年$") to listOf("Estimated crack time: about $1 trillion years"),
    Regex("^预计破解时长：(.+)$") to listOf("Estimated crack time: $1"),
    Regex("^正在检测 (\\d+)/(\\d+)$") to listOf("Checking $1/$2"),
    Regex("^收起(.+)$") to listOf("Collapse $1"),
    Regex("^展开(.+)$") to listOf("Expand $1"),
    Regex("^约 (\\d+) 秒$") to listOf("About $1 seconds"),
    Regex("^约 (\\d+) 分钟$") to listOf("About $1 minutes"),
    Regex("^约 (\\d+) 小时$") to listOf("About $1 hours"),
    Regex("^约 (\\d+) 天$") to listOf("About $1 days"),
    Regex("^约 ([\\d.]+) 年$") to listOf("About $1 years"),
    Regex("^约 ([\\d.]+) 万年$") to listOf("About $1 ten-thousand years"),
    Regex("^约 ([\\d.]+) 亿年$") to listOf("About $1 hundred-million years"),
    Regex("^约 ([\\d.]+) 万亿年$") to listOf("About $1 trillion years"),
    Regex("^TOTP · (.+) · (\\d+) 位 · (\\d+) 秒$") to listOf("TOTP · $1 · $2 digits · $3 seconds"),
    Regex("^HOTP · (.+) · (\\d+) 位 · 计数器 (\\d+)$") to listOf("HOTP · $1 · $2 digits · Counter $3"),
    Regex("^(.+)的库标识：(.+)…\\n与当前账户库不一致$") to listOf("$1 vault ID: $2…\nThis does not match the current vault"),
    Regex("^(.+)数据不带库谱系标识$") to listOf("$1 data has no vault lineage identifier and may come from an older version or a third-party export"),
    Regex("^本地字典匹配 \\+ 该密码在 Pwned Passwords 中出现过 (\\d+) 次$") to listOf("Matched a local dictionary and appeared $1 times in Pwned Passwords"),
    Regex("^已执行(.+)。第 1 组 PMRK1 是格式标识，不参与校验；以下序号按完整密钥从左到右计算，每组从 5 个候选中选择。$") to listOf("$1 completed. Group 1, PMRK1, is a format marker and is not verified. The following positions are counted from left to right across the complete key; choose one of five candidates for each group."),
    Regex("^这份(.+)数据看起来不是当前账户的同一份库。$") to listOf("This $1 data does not appear to belong to the current vault."),
    Regex("^已删除「(.+)」，30 天后自动清除，可在账户列表页恢复$") to listOf("Moved “$1” to Trash. It will be deleted automatically after 30 days and can be restored from the account list."),
    Regex("^已彻底删除「(.+)」$") to listOf("Permanently deleted “$1”"),
    Regex("^账户「(.+)」不在回收站$") to listOf("“$1” is not in Trash"),
    Regex("^已恢复并导入到账户「(.+)」$") to listOf("Restored and imported into “$1”"),
    Regex("^尝试次数过多，请等待约 (\\d+) 秒后重试$") to listOf("Too many attempts. Try again in about $1 seconds."),
    Regex("^失败次数过多，已锁定 (\\d+) 秒$") to listOf("Too many failed attempts. Unlocking is disabled for $1 seconds."),
    Regex("^加密备份已导出 (\\d+) 条$") to listOf("Encrypted backup exported $1 items"),
    Regex("^核对码：(.+)$") to listOf("Verification code: $1"),
    Regex("^请求设备：(.+)…\\n核对码：(.+)$") to listOf("Requesting device: $1…\nVerification code: $2"),
    Regex("^仅可在绑定设备 (.+) 使用$") to listOf("Usable only on bound device $1"),
    Regex("^(.+)：(.+)。导入文件含明文密码，请确认后安全删除$") to listOf("$1: $2. The import file contains plaintext passwords; delete it securely after confirming the import."),
    Regex("^(.+)连接成功$") to listOf("$1 connected"),
    Regex("^已覆盖(.+)远端文件并完成校验$") to listOf("The remote $1 file was overwritten and verified"),
    Regex("^去重：自动合并 (\\d+)，手动解决 (\\d+)，跳过 (\\d+)$") to listOf("Duplicate cleanup: $1 merged automatically, $2 resolved manually, $3 skipped"),
    Regex("^已合并 (\\d+) 条条目为「(.+)」$") to listOf("Merged $1 items into “$2”"),
    Regex("^(.+)自动云端同步连续失败3次，已暂停$") to listOf("$1 automatic cloud sync was paused after three consecutive failures"),
    Regex("^约 (\\d+) 秒$") to listOf("about $1 seconds"),
    Regex("^约 (\\d+) 分钟$") to listOf("about $1 minutes"),
    Regex("^约 (\\d+) 小时$") to listOf("about $1 hours"),
    Regex("^约 (\\d+) 天$") to listOf("about $1 days"),
    Regex("^约 ([\\d.]+) 年$") to listOf("about $1 years"),
    Regex("^约 ([\\d.]+) 万年$") to listOf("about $1 ten-thousand years"),
    Regex("^约 ([\\d.]+) 亿年$") to listOf("about $1 hundred-million years"),
    Regex("^约 ([\\d.]+) 万亿年$") to listOf("about $1 trillion years"),
    Regex("^已复制「(.+)」，不自动清理$") to listOf("Copied “$1”, not cleaned automatically"),
    Regex("^已复制「(.+)」，(\\d+) 秒后自动清理$") to listOf("Copied “$1”; cleaned in $2 seconds"),
    Regex("^「(.+)」为空，无可复制内容$") to listOf("“$1” is empty; there is nothing to copy"),
)
